/**
 * Everything on the Japan trip page. Booking references and ticket numbers
 * are deliberately left out — the page is public, and a reference plus a
 * surname is enough to open a booking on most airline sites.
 */
export type City = "tokyo" | "kyoto" | "osaka" | "travel";
export type Row = [label: string, text: string];
/** "i" = from the agent's itinerary, "x" = planned by Dhairya. `place` points at a card in `places`. */
export type Entry = [time: string, text: string, kind: "i" | "x", place?: string];
/** Somewhere to eat, shop, see or get to — shown as a card beside the day. */
export type Place = {
  id: string;
  t: string;
  type: string;
  name: string;
  what: string;
  dist: string;
  hours: string;
  note: string;
  url: string;
};
export type Day = {
  date: string;
  city: City;
  title: string;
  /** The line under the date on the day buttons. */
  short: string;
  gist: string;
  timeline: Entry[];
  places: Place[];
  tips: Row[];
  sleep: string;
};

export const DAYS: Day[] = [
  {
    date: "2026-10-19", city: "travel", title: "Fly to Japan", short: "Fly to Japan",
    gist: "Air India. 13h 30m, 1 stop in Delhi.",
    timeline: [
      ["07:30", "Wake up. Final check: passports, visas, Visit Japan Web QR codes, hotel details, return ticket printout", "x"],
      ["09:30", "Leave home for Kolkata airport", "x"],
      ["10:30", "Check in for both flights. Confirm bags are tagged all the way to Tokyo (HND)", "x"],
      ["12:55", "AI 1874 departs Kolkata (CCU)", "i"],
      ["~15:30", "Land in Delhi. Follow international transfer signs to T3 for emigration and security (time from Air India's schedule, check the app)", "x"],
      ["Delhi", "1 stop in Delhi (DEL), change to AI 358", "i"],
      ["~18:15", "AI 358 departs Delhi (time from Air India's schedule)", "x"],
      ["On board", "Meals complimentary", "i"],
      ["~20:30", "Set your watch to Japan time (+3:30) and sleep as much as you can", "x"],
      ["05:55", "Land at Haneda Terminal 3, Tue 20 Oct (Tokyo time)", "i"],
    ],
    places: [

    ],
    tips: [["Seats", "Your booking shows seats only partly selected. Pick seats together at web check-in."]],
    sleep: "On the plane (Delhi → Tokyo)",
  },
  {
    date: "2026-10-20", city: "tokyo", title: "Tokyo arrival, half-day tour", short: "Tokyo arrival, half-day tour",
    gist: "Tokyo Arrival. Tokyo SIC (shared group) half-day tour.",
    timeline: [
      ["05:55", "Land at Haneda Terminal 3", "i"],
      ["06:00", "Immigration, customs, collect bags (about 1 hour)", "x"],
      ["07:00", "Private airport transfer to the hotel (about 40 min)", "i"],
      ["07:45", "Reach the hotel, leave bags at the front desk", "x"],
      ["08:00", "Breakfast: egg sandwich", "x", "seven"],
      ["09:00", "Slow walk in Shinjuku Gyoen garden (opens 9 am)", "x", "gyoen"],
      ["10:45", "Rest in the hotel lobby", "x"],
      ["12:00–13:00", "Room ready (earlier if available). Official check-in is 3 pm", "i"],
      ["12:15", "Lunch", "x", "ain"],
      ["13:15", "Freshen up, short rest", "x"],
      ["13:40", "Leave for the tour pickup point (not confirmed yet)", "x"],
      ["14:00", "Tour starts (3–4 hours)", "i"],
      ["", "Imperial Palace Plaza (photo stop)", "i"],
      ["", "Senso-ji Temple and Nakamise Shopping Street (shopping time, max 1 hour)", "i", "naka"],
      ["", "Kabukiza (drive-by)", "i"],
      ["", "National Diet Building (drive-by)", "i"],
      ["", "Tokyo Tower Main Deck (photo stop)", "i"],
      ["~17:30", "Tour ends", "i"],
      ["18:30", "Shoes", "x", "abc"],
      ["19:15", "Uniqlo, GU and Bic Camera", "x", "bic"],
      ["20:15", "Dinner: ramen", "x", "afuri"],
      ["21:15", "Back to the hotel (taxi about 10 min, or 20 min walk)", "x"],
      ["21:30", "Shower, lay out warm layers for Mt. Fuji", "x"],
      ["22:30", "Sleep (8 hours before the 6:30 alarm)", "x"],
    ],
    places: [
      { id: "seven", t: "08:00", type: "Eat", name: "7-Eleven Shinjuku 1-chome", what: "Egg sandwich (tamago sando) for breakfast",
        dist: "50 m from the hotel · 1 min", hours: "Open 24 hours", note: "",
        url: "https://www.google.com/maps/dir/?api=1&origin=Citadines+Shinjuku+Tokyo&origin_place_id=ChIJw3B7QeiMGGARMd-dUShWkFU&destination=7-Eleven+Shinjuku+1-chome&destination_place_id=ChIJDwGrFeiMGGARLCeEfqSx1T0&travelmode=walking" },
      { id: "gyoen", t: "09:00–10:30", type: "See", name: "Shinjuku Gyoen National Garden", what: "Huge, calm garden with ponds and lawns. Easy walk while the room isn't ready",
        dist: "About 700 m from the hotel · 10 min", hours: "Tue 9 am–4:30 pm", note: "Entry about ¥500",
        url: "https://www.google.com/maps/dir/?api=1&origin=Citadines+Shinjuku+Tokyo&origin_place_id=ChIJw3B7QeiMGGARMd-dUShWkFU&destination=Shinjuku+Gyoen+National+Garden&destination_place_id=ChIJPyOTG8KMGGARh_IXobWxHmo&travelmode=walking" },
      { id: "ain", t: "12:15", type: "Eat", name: "Ain Soph Journey", what: "Fully vegan cafe: pancakes, set lunches",
        dist: "About 650 m from the hotel · 9 min", hours: "Tue lunch until 4 pm", note: "Gets busy; book a table online",
        url: "https://www.google.com/maps/dir/?api=1&origin=Citadines+Shinjuku+Tokyo&origin_place_id=ChIJw3B7QeiMGGARMd-dUShWkFU&destination=Ain+Soph+Journey+Shinjuku&destination_place_id=ChIJyUynodyMGGARfdwk4A8pub8&travelmode=walking" },
      { id: "naka", t: "During the tour", type: "Shop", name: "Nakamise Street", what: "Souvenirs: fans, keychains, chopsticks",
        dist: "On the way into Senso-ji", hours: "Stalls close around 5 pm", note: "Link starts at Senso-ji",
        url: "https://www.google.com/maps/dir/?api=1&origin=Senso-ji+Temple+Asakusa&destination=Nakamise+Shopping+Street&destination_place_id=ChIJPd37MMGOGGARvJ2hfxoiNVE&travelmode=walking" },
      { id: "chacha", t: "During the tour", type: "Eat", name: "Chacha Futatsume", what: "Signature matcha ice cream cone, about ¥1,700, big enough to share",
        dist: "About 260 m from Senso-ji, near Kaminarimon gate", hours: "Until 6 pm", note: "Takeaway, fits inside the 1 hour. Sponge layer usually has egg",
        url: "https://www.google.com/maps/dir/?api=1&origin=Senso-ji+Temple+Asakusa&destination=Chacha+Futatsume&destination_place_id=ChIJI6WnnQuPGGARdCd19Rz8wbQ&travelmode=walking" },
      { id: "abc", t: "18:30", type: "Shop", name: "ABC-Mart Premier Stage", what: "Shoes: Nike, Adidas, New Balance, Asics",
        dist: "About 800 m from the hotel · 10 min", hours: "Closes 9 pm", note: "Go here first, it closes earliest",
        url: "https://www.google.com/maps/dir/?api=1&origin=Citadines+Shinjuku+Tokyo&origin_place_id=ChIJw3B7QeiMGGARMd-dUShWkFU&destination=ABC-MART+Premier+Stage+Shinjuku+3-chome&destination_place_id=ChIJoy4PhduMGGARKoS1r54Rdro&travelmode=walking" },
      { id: "bic", t: "19:15", type: "Shop", name: "Uniqlo flagship, GU, Bic Camera", what: "Clothes and gadgets, all in one building",
        dist: "About 300 m from ABC-Mart · 4 min", hours: "Until 10 pm", note: "",
        url: "https://www.google.com/maps/dir/?api=1&origin=ABC-MART+Premier+Stage+Shinjuku+3-chome&origin_place_id=ChIJoy4PhduMGGARKoS1r54Rdro&destination=Uniqlo+Shinjuku+Honten&destination_place_id=ChIJCT-INACNGGARWLBECvtQoNI&travelmode=walking" },
      { id: "afuri", t: "20:15", type: "Eat", name: "Afuri Shinjuku Lumine", what: "Vegan yuzu ramen (look for the vegan button on the ticket machine)",
        dist: "About 400 m from Bic Camera · 6 min", hours: "Until 10 pm", note: "About 1.5 km back to the hotel",
        url: "https://www.google.com/maps/dir/?api=1&origin=Uniqlo+Shinjuku+Honten&origin_place_id=ChIJCT-INACNGGARWLBECvtQoNI&destination=Afuri+Shinjuku+Lumine&destination_place_id=ChIJq6qq-dCMGGARmyGicupYD2Y&travelmode=walking" },
    ],
    tips: [["Not confirmed yet", "Tour pickup point and where it drops you. Evening times assume you're back in Shinjuku by 6 pm."]],
    sleep: "Citadines Shinjuku, Tokyo",
  },
  {
    date: "2026-10-21", city: "tokyo", title: "Mt. Fuji and Hakone", short: "Mt. Fuji and Hakone",
    gist: "Tokyo SIC: Mt. Fuji and Hakone Tour [Return by Shinkansen] With Lunch (From Shinjuku).",
    timeline: [
      ["06:30", "Wake up", "x"],
      ["07:00", "Hotel breakfast", "x"],
      ["07:45", "Leave for the tour start (starting point to be announced)", "x"],
      ["08:15", "Tour starts", "i"],
      ["", "Mt. Fuji 5th Station", "i"],
      ["", "Lunch (included)", "i"],
      ["", "Hakone Ropeway", "i"],
      ["", "Return by Shinkansen", "i"],
      ["20:00", "Tour ends at Tokyo Station", "i"],
      ["20:15", "Dinner: vegan ramen inside the station", "x", "tans"],
      ["21:15", "Marunouchi line straight to Shinjuku-gyoemmae (about 20 min)", "x", "back"],
      ["21:45", "Back at the hotel, rest", "x"],
      ["22:45", "Sleep", "x"],
    ],
    places: [
      { id: "tans", t: "20:15", type: "Eat", name: "T's Tantan", what: "Fully vegan ramen and gyoza",
        dist: "Inside Tokyo Station, Gransta B1F, outside the ticket gates", hours: "Until 10 pm", note: "Hard to find; ask staff for \"Gransta B1\"",
        url: "https://www.google.com/maps/dir/?api=1&origin=Citadines+Shinjuku+Tokyo&origin_place_id=ChIJw3B7QeiMGGARMd-dUShWkFU&destination=T%27s+Tantan+Tokyo+Station&destination_place_id=ChIJtTLL9fuLGGARm6IP54k3xn4&travelmode=transit" },
      { id: "back", t: "21:15", type: "Go", name: "Route back to the hotel", what: "Marunouchi line, no change",
        dist: "About 20–25 min door to door", hours: "", note: "",
        url: "https://www.google.com/maps/dir/?api=1&origin=T%27s+Tantan+Tokyo+Station&origin_place_id=ChIJtTLL9fuLGGARm6IP54k3xn4&destination=Citadines+Shinjuku+Tokyo&destination_place_id=ChIJw3B7QeiMGGARMd-dUShWkFU&travelmode=transit" },
    ],
    tips: [["Not confirmed yet", "Tour starting point."], ["Dress warm", "Layers and a jacket for the 5th Station."]],
    sleep: "Citadines Shinjuku, Tokyo",
  },
  {
    date: "2026-10-22", city: "tokyo", title: "Tokyo Disneyland", short: "Tokyo Disneyland",
    gist: "Tokyo – Disney transfer (two way, private). Disneyland entry ticket only, with transfers.",
    timeline: [
      ["07:00", "Wake up", "x"],
      ["07:30", "Hotel breakfast", "x"],
      ["08:15", "Private transfer to Disneyland (pickup time to confirm)", "i"],
      ["09:00", "Tokyo Disneyland (entry ticket included). Check park hours for the day", "i"],
      ["13:00", "Lunch inside the park (paid separately)", "x"],
      ["16:00", "Snack and rest break", "x"],
      ["19:30", "Private transfer back to the hotel (time to confirm)", "i"],
      ["20:30", "Dinner: curry rice", "x", "coco_t"],
      ["21:15", "Souvenirs and snacks", "x", "donki"],
      ["22:00", "Back to the hotel. Pack: you check out tomorrow", "x"],
      ["23:00", "Sleep", "x"],
    ],
    places: [
      { id: "coco_t", t: "20:30", type: "Eat", name: "CoCo Ichibanya Shinjuku 2-chome", what: "Japanese curry rice",
        dist: "About 350 m from the hotel · 5 min", hours: "Until 11 pm", note: "Ask for the separate vegetarian menu",
        url: "https://www.google.com/maps/dir/?api=1&origin=Citadines+Shinjuku+Tokyo&origin_place_id=ChIJw3B7QeiMGGARMd-dUShWkFU&destination=CoCo+Ichibanya+Shinjuku+2-chome&destination_place_id=ChIJCSlcwsKMGGARBi3AfgAp8R4&travelmode=walking" },
      { id: "donki", t: "21:15", type: "Shop", name: "Don Quijote Shinjuku Tonanguchi", what: "8 floors: souvenirs, snacks, funny t-shirts",
        dist: "About 800 m from CoCo · 10 min", hours: "Open 24 hours", note: "Bring passports for tax-free. About 1.2 km back to the hotel",
        url: "https://www.google.com/maps/dir/?api=1&origin=CoCo+Ichibanya+Shinjuku+2-chome&origin_place_id=ChIJCSlcwsKMGGARBi3AfgAp8R4&destination=Don+Quijote+Shinjuku+Tonanguchi&destination_place_id=ChIJ18MWiNqMGGARsZO5vEUCONc&travelmode=walking" },
    ],
    tips: [["Ask the agent", "Pickup and return times for the Disney transfer."]],
    sleep: "Citadines Shinjuku, Tokyo",
  },
  {
    date: "2026-10-23", city: "kyoto", title: "teamLab, Harajuku, bullet train to Kyoto", short: "Bullet train to Kyoto",
    gist: "Morning teamLab and shopping in Tokyo, then the 4 pm bullet train to Kyoto.",
    timeline: [
      ["06:45", "Wake up", "x"],
      ["07:10", "Hotel breakfast", "x"],
      ["07:45", "Check out from the hotel. Leave bags at the front desk", "i"],
      ["07:55", "Taxi to teamLab (15–20 min)", "x"],
      ["08:30–11:00", "teamLab (Tokyo), 2–3 hours", "i", "bl"],
      ["11:00", "Taxi to Harajuku (about 15 min)", "x", "tk"],
      ["11:20", "Shopping", "i", "wego"],
      ["11:50", "Anime and character goods", "x", "kiddy"],
      ["12:45", "Lunch", "x", "jang"],
      ["13:40", "Train or taxi back to the hotel (about 20 min)", "x"],
      ["14:00", "Collect bags, rest in the lobby", "x"],
      ["14:30", "Station transfer (private)", "i"],
      ["16:00", "Bullet train to Kyoto (tickets included)", "i"],
      ["~18:15", "Arrive at Kyoto Station", "x"],
      ["18:30", "Check in at the Kyoto hotel", "i"],
      ["19:15", "Dinner: Indian", "x", "dana"],
      ["20:45", "Back at the hotel, rest", "x"],
      ["22:00", "Sleep (tour pickup 8–8:30 am)", "x"],
    ],
    places: [
      { id: "bl", t: "08:30–11:00", type: "See", name: "teamLab Borderless", what: "Digital art museum, rooms of light and sound",
        dist: "About 4 km from the hotel · taxi 15–20 min", hours: "Opens 8:30 am", note: "Book the 8:30 entry in advance. Free lockers inside",
        url: "https://www.google.com/maps/dir/?api=1&origin=Citadines+Shinjuku+Tokyo&origin_place_id=ChIJw3B7QeiMGGARMd-dUShWkFU&destination=teamLab+Borderless+Azabudai+Hills&destination_place_id=ChIJQ5Sa1PqJGGARUSaNKKOrMVg&travelmode=transit" },
      { id: "tk", t: "11:00", type: "Go", name: "Takeshita Street, Harajuku", what: "Taxi from teamLab",
        dist: "About 3.6 km · 15 min", hours: "", note: "",
        url: "https://www.google.com/maps/dir/?api=1&origin=teamLab+Borderless+Azabudai+Hills&origin_place_id=ChIJQ5Sa1PqJGGARUSaNKKOrMVg&destination=Takeshita+Street+Harajuku&destination_place_id=ChIJlVne8bqMGGARtX5O6ojMvsI&travelmode=driving" },
      { id: "wego", t: "11:20", type: "Shop", name: "WEGO Harajuku", what: "Cheap, fun street fashion",
        dist: "On Takeshita Street", hours: "Opens 10:30 am", note: "",
        url: "https://www.google.com/maps/dir/?api=1&origin=Takeshita+Street+Harajuku&origin_place_id=ChIJlVne8bqMGGARtX5O6ojMvsI&destination=WEGO+Harajuku&destination_place_id=ChIJKx4CWaOMGGARoZCHUKj3nnM&travelmode=walking" },
      { id: "kiddy", t: "11:50", type: "Shop", name: "Kiddy Land", what: "Pokémon, Ghibli, Sanrio, Chiikawa goods",
        dist: "About 400 m from WEGO · 6 min", hours: "Opens 11 am", note: "Pay on each floor",
        url: "https://www.google.com/maps/dir/?api=1&origin=WEGO+Harajuku&origin_place_id=ChIJKx4CWaOMGGARoZCHUKj3nnM&destination=Kiddy+Land+Harajuku&destination_place_id=ChIJu1uP9aOMGGARiZH5QxSqDm0&travelmode=walking" },
      { id: "jang", t: "12:45", type: "Eat", name: "Vegan Bistro Jangara", what: "Vegan ramen, curry and gyoza, rated 4.7",
        dist: "About 400 m from Kiddy Land, opposite Harajuku Station (2F, above FamilyMart)", hours: "11 am–9 pm", note: "",
        url: "https://www.google.com/maps/dir/?api=1&origin=Kiddy+Land+Harajuku&origin_place_id=ChIJu1uP9aOMGGARiZH5QxSqDm0&destination=Vegan+Bistro+Jangara+Harajuku&destination_place_id=ChIJaWQvzaiNGGARhBHfiQXyKWs&travelmode=walking" },
      { id: "dana", t: "19:15", type: "Eat", name: "Dana Pani En", what: "Indian: paneer, aloo baingan",
        dist: "About 1.4 km from the Kyoto hotel · 18 min", hours: "Dinner until 9:30 pm", note: "",
        url: "https://www.google.com/maps/dir/?api=1&origin=Rihga+Royal+Hotel+Kyoto&origin_place_id=ChIJ2_bqcpUIAWARCxsfbw83nEY&destination=Dana+Pani+En&destination_place_id=ChIJK48KUVUPAWARc5ccxzhHEPs&travelmode=walking" },
    ],
    tips: [["Package note", "Intercity baggage transfer is not included."], ["Be back by 2:30 pm", "For the station transfer."]],
    sleep: "RIHGA Royal Hotel, Kyoto",
  },
  {
    date: "2026-10-24", city: "kyoto", title: "Nara, Fushimi Inari, Arashiyama", short: "Nara, Fushimi Inari, Arashiyama",
    gist: "Nara, Fushimi Inari Taisha, Arashiyama bus tour.",
    timeline: [
      ["06:30", "Wake up", "x"],
      ["07:00", "Hotel breakfast", "x"],
      ["07:45", "Ready in the lobby", "x"],
      ["08:00–08:30", "Tour starts", "i"],
      ["", "Nara", "i"],
      ["", "Fushimi Inari Taisha", "i"],
      ["", "Arashiyama", "i"],
      ["Evening", "Tour ends (end time not given)", "i"],
      ["After tour", "Rest at the hotel for an hour", "x"],
      ["19:30", "Dinner: curry rice", "x", "coco_k"],
      ["20:30", "Gadgets and gachapon", "x", "yodo"],
      ["21:30", "Back to the hotel, pack", "x"],
      ["22:30", "Sleep", "x"],
    ],
    places: [
      { id: "coco_k", t: "19:30", type: "Eat", name: "CoCo Ichibanya Hachijo Entrance", what: "Japanese curry rice",
        dist: "About 1 km from the hotel · 13 min", hours: "Until midnight", note: "Ask for the vegetarian menu",
        url: "https://www.google.com/maps/dir/?api=1&origin=Rihga+Royal+Hotel+Kyoto&origin_place_id=ChIJ2_bqcpUIAWARCxsfbw83nEY&destination=CoCo+Ichibanya+Hachijo+Entrance&destination_place_id=ChIJk8GcG60IAWARmjRXG5ZxYD8&travelmode=walking" },
      { id: "yodo", t: "20:30", type: "Shop", name: "Yodobashi Camera Kyoto", what: "Gadgets, gachapon capsule toys, anime goods",
        dist: "About 700 m from CoCo, through Kyoto Station", hours: "Until 10 pm", note: "About 650 m back to the hotel",
        url: "https://www.google.com/maps/dir/?api=1&origin=CoCo+Ichibanya+Hachijo+Entrance&origin_place_id=ChIJk8GcG60IAWARmjRXG5ZxYD8&destination=Yodobashi+Camera+Multimedia+Kyoto&destination_place_id=ChIJNfpddK8IAWAR21KSO4M57nY&travelmode=walking" },
    ],
    tips: [["Comfortable shoes", "Lots of walking at Fushimi Inari."]],
    sleep: "RIHGA Royal Hotel, Kyoto",
  },
  {
    date: "2026-10-25", city: "osaka", title: "Kyoto to Osaka, Shinsaibashi and Dotonbori", short: "Bullet train to Osaka",
    gist: "Kyoto to Osaka by bullet train.",
    timeline: [
      ["07:30", "Wake up (slower morning)", "x"],
      ["08:00", "Hotel breakfast", "x"],
      ["09:00", "Morning walk", "x", "hongan"],
      ["10:15", "Back at the hotel, finish packing", "x"],
      ["11:00", "Check out", "x"],
      ["11:30", "Walk to Kyoto Station", "x"],
      ["12:00", "Bullet train to Osaka", "i"],
      ["~12:15", "Arrive Shin-Osaka, Midosuji line to Hommachi (about 15 min)", "x"],
      ["13:00", "Drop bags at the Osaka hotel", "x"],
      ["13:10", "Lunch", "x", "coco_o"],
      ["14:00", "Rest at the hotel", "x"],
      ["15:00", "Pokémon Center", "x", "pkm"],
      ["15:45", "Shoes", "x", "asics"],
      ["16:30", "Vintage clothes", "x", "jam"],
      ["17:30", "Walk down the Shinsaibashi-suji arcade towards Namba", "x"],
      ["18:00", "Dinner: omurice", "x", "hk"],
      ["19:00", "Glico sign photo", "x", "ebisu"],
      ["19:15", "River cruise", "x", "tombori"],
      ["19:45", "Lantern lane", "x", "hozen"],
      ["20:00", "Dessert: taiyaki", "x", "naruto"],
      ["20:30", "Metro Namba → Hommachi (2 stops)", "x"],
      ["21:00", "Back at the hotel, rest", "x"],
      ["22:30", "Sleep", "x"],
    ],
    places: [
      { id: "hongan", t: "09:00–10:15", type: "See", name: "Higashi Hongan-ji", what: "One of the largest wooden temple halls in the world. Calm, free",
        dist: "About 800 m from the hotel · 10 min", hours: "Opens 5:50 am", note: "Shoes off inside; shoulders and knees covered",
        url: "https://www.google.com/maps/dir/?api=1&origin=Rihga+Royal+Hotel+Kyoto&origin_place_id=ChIJ2_bqcpUIAWARCxsfbw83nEY&destination=Higashi+Hongan-ji&destination_place_id=ChIJkWH_sqUIAWARWsn28jWc7y0&travelmode=walking" },
      { id: "coco_o", t: "13:10", type: "Eat", name: "CoCo Ichibanya Honmachi 4-chome", what: "Quick curry rice lunch",
        dist: "About 110 m from the Osaka hotel", hours: "Until 10 pm", note: "Ask for the vegetarian menu",
        url: "https://www.google.com/maps/dir/?api=1&origin=Osaka+View+Hotel+Honmachi&origin_place_id=ChIJDYCo9OLmAGARHahlNEJ5nhQ&destination=CoCo+Ichibanya+Honmachi+4-chome&destination_place_id=ChIJ_UBzl-LmAGAROd5c6aTbeDg&travelmode=walking" },
      { id: "pkm", t: "15:00", type: "Shop", name: "Pokémon Center Osaka DX", what: "Osaka-only pins, cards, plushies. One Piece shop on the same floor",
        dist: "Daimaru Shinsaibashi 9F · about 1.25 km, or 1 metro stop", hours: "Until 8 pm", note: "",
        url: "https://www.google.com/maps/dir/?api=1&origin=Osaka+View+Hotel+Honmachi&origin_place_id=ChIJDYCo9OLmAGARHahlNEJ5nhQ&destination=Pokemon+Center+Osaka+DX&destination_place_id=ChIJiZ8OQInnAGART2BGEGqySKk&travelmode=walking" },
      { id: "asics", t: "15:45", type: "Shop", name: "Asics Shinsaibashi", what: "Shoes",
        dist: "About 100 m across the arcade", hours: "Until 8 pm", note: "Buy shoes here rather than Tokyo, less to carry",
        url: "https://www.google.com/maps/dir/?api=1&origin=Pokemon+Center+Osaka+DX&origin_place_id=ChIJiZ8OQInnAGART2BGEGqySKk&destination=asics+Osaka+Shinsaibashi&destination_place_id=ChIJE0F1JxHnAGARp2gpTuFLvhE&travelmode=walking" },
      { id: "jam", t: "16:30", type: "Shop", name: "JAM Amerikamura", what: "Vintage shirts and pants, rated 4.8",
        dist: "About 300 m from Asics", hours: "Until 8 pm", note: "Skip if running late",
        url: "https://www.google.com/maps/dir/?api=1&origin=asics+Osaka+Shinsaibashi&origin_place_id=ChIJE0F1JxHnAGARp2gpTuFLvhE&destination=JAM+Amerika-mura+2nd+Store&destination_place_id=ChIJ_SbkeCDnAGARdgGFBWA0Bc8&travelmode=walking" },
      { id: "hk", t: "18:00", type: "Eat", name: "Hokkyokusei Namba", what: "Omurice, from the family that invented it",
        dist: "Takashimaya B1F · about 1.1 km from JAM", hours: "Closes 8 pm", note: "Ask for the vegetarian omurice",
        url: "https://www.google.com/maps/dir/?api=1&origin=JAM+Amerika-mura+2nd+Store&origin_place_id=ChIJ_SbkeCDnAGARdgGFBWA0Bc8&destination=Hokkyokusei+Namba&destination_place_id=ChIJ3eR2kGznAGARr0Fl25AeyHA&travelmode=walking" },
      { id: "ebisu", t: "19:00", type: "See", name: "Ebisu Bridge", what: "The Glico running man sign and Dotonbori neon",
        dist: "About 500 m from Hokkyokusei", hours: "", note: "",
        url: "https://www.google.com/maps/dir/?api=1&origin=Hokkyokusei+Namba&origin_place_id=ChIJ3eR2kGznAGARr0Fl25AeyHA&destination=Ebisu+Bridge&destination_place_id=ChIJdyYZhBPnAGARPF9WeVTYbZM&travelmode=walking" },
      { id: "tombori", t: "19:15", type: "See", name: "Tombori River Cruise", what: "20 min boat ride under the neon",
        dist: "Pier next to Ebisu Bridge", hours: "Last boats around 9 pm", note: "About ¥2,000; queues grow later",
        url: "https://www.google.com/maps/dir/?api=1&origin=Ebisu+Bridge&origin_place_id=ChIJdyYZhBPnAGARPF9WeVTYbZM&destination=Tombori+River+Cruise&destination_place_id=ChIJ2ySFjBTnAGAR3ngfXW-dwaU&travelmode=walking" },
      { id: "hozen", t: "19:45", type: "See", name: "Hozenji Yokocho", what: "Quiet stone lane with lanterns and a moss-covered shrine",
        dist: "About 100 m from the pier", hours: "", note: "",
        url: "https://www.google.com/maps/dir/?api=1&origin=Tombori+River+Cruise&origin_place_id=ChIJ2ySFjBTnAGAR3ngfXW-dwaU&destination=Hozenji+Yokocho&destination_place_id=ChIJY4ZQxRTnAGAR0mjfWQwO7ho&travelmode=walking" },
      { id: "naruto", t: "20:00", type: "Eat", name: "Naruto Taiyaki Hompo", what: "Fish-shaped cake with red bean or custard",
        dist: "About 200 m from Hozenji", hours: "Until 5 am", note: "Namba Station is about 400 m away",
        url: "https://www.google.com/maps/dir/?api=1&origin=Hozenji+Yokocho&origin_place_id=ChIJY4ZQxRTnAGAR0mjfWQwO7ho&destination=Naruto+Taiyaki+Hompo+Osaka&destination_place_id=ChIJ63rK2mrnAGARmhZZX0xYTw0&travelmode=walking" },
    ],
    tips: [["Package note", "Intercity baggage transfer is not included."], ["Shops close at 8 pm", "If you're running late, drop JAM first."]],
    sleep: "Osaka View Hotel Honmachi",
  },
  {
    date: "2026-10-26", city: "osaka", title: "Osaka walking tour", short: "Osaka walking tour",
    gist: "Osaka SIC: 1-Day Osaka Walking Tour with Western-style Lunch (round trip from Osaka-Umeda).",
    timeline: [
      ["07:30", "Wake up", "x"],
      ["08:00", "Hotel breakfast", "x"],
      ["09:05", "Leave the hotel. Midosuji line Hommachi → Umeda (3 stops)", "x", "respire"],
      ["09:40", "Tour starts at Hotel Hankyu Respire Osaka", "i"],
      ["", "Floating Garden Observatory", "i"],
      ["Lunch", "Western-style set menu at Hotel Hankyu Respire Osaka", "i"],
      ["", "Board the Aqua Liner", "i"],
      ["", "Osaka Castle", "i"],
      ["17:45", "Tour ends at Higashi-Umeda Station", "i"],
      ["18:15", "Collectibles in Den Den Town", "x", "suru"],
      ["19:30", "Dinner: okonomiyaki", "x", "chibo"],
      ["20:45", "Metro Namba → Hommachi", "x"],
      ["21:15", "Rest, start packing", "x"],
      ["22:30", "Sleep", "x"],
    ],
    places: [
      { id: "respire", t: "09:05", type: "Go", name: "Hotel Hankyu Respire Osaka (tour start)", what: "Midosuji line to Umeda",
        dist: "About 25 min door to door", hours: "", note: "Be there by 9:30",
        url: "https://www.google.com/maps/dir/?api=1&origin=Osaka+View+Hotel+Honmachi&origin_place_id=ChIJDYCo9OLmAGARHahlNEJ5nhQ&destination=Hotel+Hankyu+Respire+Osaka&travelmode=transit" },
      { id: "suru", t: "18:15", type: "Shop", name: "SURUGA-YA Nipponbashi", what: "Figures, games, cards, manga",
        dist: "About 30 min by train from Higashi-Umeda", hours: "Until 9 pm", note: "Most other Den Den Town shops close around 7 pm",
        url: "https://www.google.com/maps/dir/?api=1&origin=Higashi-Umeda+Station&destination=SURUGA-YA+Osaka+Nipponbashi&destination_place_id=ChIJ51SvEWjnAGARPA6EuPAVGDU&travelmode=transit" },
      { id: "chibo", t: "19:30", type: "Eat", name: "CHIBO Dotonbori", what: "Okonomiyaki, Osaka's savoury pancake",
        dist: "About 950 m from Suruga-ya · 13 min", hours: "Until 11 pm", note: "Ask for no meat, seafood or bonito flakes",
        url: "https://www.google.com/maps/dir/?api=1&origin=SURUGA-YA+Osaka+Nipponbashi&origin_place_id=ChIJ51SvEWjnAGARPA6EuPAVGDU&destination=CHIBO+Dotonbori&destination_place_id=ChIJk9v34BTnAGAR8SL3pWF-3Js&travelmode=walking" },
    ],
    tips: [["Package note", "Vegetarian meals are available and must be requested at the time of booking."]],
    sleep: "Osaka View Hotel Honmachi",
  },
  {
    date: "2026-10-27", city: "osaka", title: "Universal Studios Japan", short: "Universal Studios Japan",
    gist: "Osaka – Universal Studios (pick and drop transfer, private). Entry ticket only.",
    timeline: [
      ["07:00", "Wake up", "x"],
      ["07:30", "Hotel breakfast", "x"],
      ["08:15", "Private pickup to Universal Studios (time to confirm)", "i"],
      ["09:00", "Universal Studios Japan (entry ticket included). Check park hours for the day", "i"],
      ["13:00", "Lunch inside the park (paid separately)", "x"],
      ["16:00", "Snack and rest break", "x"],
      ["19:00", "Private drop to the hotel (time to confirm)", "i"],
      ["19:45", "Dinner", "x", "paprika"],
      ["21:00", "Pack. Return flight allows 20 kg check-in and 7 kg cabin each", "x"],
      ["22:30", "Sleep", "x"],
    ],
    places: [
      { id: "paprika", t: "19:45", type: "Eat", name: "Paprika Shokudo Vegan", what: "Fully vegan: burgers, gyoza, set meals, rated 4.6",
        dist: "About 1 km from the hotel · 12 min", hours: "Tue dinner 5:30–9 pm", note: "If you're back late: CoCo Ichibanya across the street, until 10 pm",
        url: "https://www.google.com/maps/dir/?api=1&origin=Osaka+View+Hotel+Honmachi&origin_place_id=ChIJDYCo9OLmAGARHahlNEJ5nhQ&destination=Paprika+Shokudo+Vegan&destination_place_id=ChIJ72nbqATnAGAR8GMxZxz0qNw&travelmode=walking" },
    ],
    tips: [["Ask the agent", "Pickup and drop times for the Universal Studios transfer."]],
    sleep: "Osaka View Hotel Honmachi",
  },
  {
    date: "2026-10-28", city: "travel", title: "Fly home (Dad to China)", short: "Fly home (Dad to China)",
    gist: "Airport transfer, one way (private). Thai Vietjet, 1 stop in Bangkok. Dhairya and Sweta fly home. Dad flies on to China separately.",
    timeline: [
      ["06:45", "Wake up", "x"],
      ["07:15", "Hotel breakfast", "x"],
      ["08:00", "Check out", "x"],
      ["08:15", "Private transfer to the airport (time to confirm)", "i"],
      ["~09:15", "Reach Kansai (KIX), check in. 20 kg check-in, 7 kg cabin", "x"],
      ["12:00", "VZ 567 departs Kansai (KIX)", "i"],
      ["18:10", "Lands Bangkok (BKK), 4h 20m layover, change planes", "i"],
      ["22:30", "VZ 770 departs Bangkok", "i"],
      ["23:50", "Lands Kolkata (CCU)", "i"],
    ],
    places: [

    ],
    tips: [["Itinerary error", "The itinerary says transfer from Narita. Your flight leaves from Kansai (KIX)."], ["Baggage", "Cabin 7 kg and check-in 20 kg per adult."]],
    sleep: "Home",
  },
];

export const FLIGHTS = [
  {
    route: "Kolkata → Delhi → Tokyo",
    when: "Mon 19 Oct · 12:55 → Tue 20 Oct 05:55",
    lines: [
      "AI 1874 Kolkata → Delhi, then AI 358 → Haneda T3",
      "13h 30m, 1 stop in Delhi",
      "Meals complimentary",
    ],
    who: "Dhairya, Dilip and Sweta Khetan",
  },
  {
    route: "Osaka → Bangkok → Kolkata",
    when: "Wed 28 Oct · 12:00 → 23:50 same night",
    lines: [
      "Thai Vietjet VZ 567 from Kansai (KIX), 4h 20m stop in Bangkok, then VZ 770",
      "20 kg check-in + 7 kg cabin each",
    ],
    who: "Dhairya and Sweta Khetan. Dad flies on to China separately.",
  },
];

export const HOTELS: { nights: string; name: string; room: string; city: City }[] = [
  { nights: "20, 21, 22 Oct", name: "Citadines Shinjuku, Tokyo", room: "Standard double, breakfast included", city: "tokyo" },
  { nights: "23, 24 Oct", name: "RIHGA Royal Hotel, Kyoto", room: "Standard room, breakfast included", city: "kyoto" },
  { nights: "25, 26, 27 Oct", name: "Osaka View Hotel Honmachi", room: "Standard triple, breakfast included", city: "osaka" },
];

export const TODO = [
  "Last-day airport transfer goes to Kansai (KIX), not Narita, and its time.",
  "All 8 hotel nights booked (package says 7 nights).",
  "Pickup point for the Tokyo half-day tour (20 Oct).",
  "Starting point for the Mt. Fuji tour (21 Oct).",
  "Pickup and return times for Disney (22 Oct) and Universal Studios (27 Oct).",
  "Vegetarian lunch on the Osaka tour must be requested at booking.",
  "Dad's ride to the airport on 28 Oct.",
];
