/**
 * Everything on the Japan trip page. Booking references and ticket numbers
 * are deliberately left out — the page is public, and a reference plus a
 * surname is enough to open a booking on most airline sites.
 */
export type City = "tokyo" | "kyoto" | "osaka" | "travel";
export type Row = [label: string, text: string];
/** "i" = from the agent's itinerary, "x" = planned by Dhairya. `place` points at a card in `places`. */
export type Entry = [time: string, text: string, kind: "i" | "x", place?: string];
/** Somewhere to eat, shop, see or get to — shown as a card beside the day. */
export type Place = {
  id: string;
  t: string;
  type: string;
  name: string;
  what: string;
  dist: string;
  hours: string;
  note: string;
  url: string;
};
export type Day = {
  date: string;
  city: City;
  title: string;
  /** The line under the date on the day buttons. */
  short: string;
  gist: string;
  timeline: Entry[];
  places: Place[];
  tips: Row[];
  sleep: string;
};

export const DAYS: Day[] = [
  {
    date: "2026-10-19", city: "travel", title: "Fly to Japan", short: "Fly to Japan",
    gist: "Air India. 13h 30m, 1 stop in Delhi.",
    timeline: [
      ["07:30","Final check: passports, visas, Visit Japan Web QR codes, hotel list, return ticket printout, some yen, plug adapter (Japan uses flat two-pin, 100 V)","x"],
      ["09:30","Leave home for Kolkata airport","x"],
      ["10:00","Check in for both flights. Make sure bags are tagged through to Haneda (HND) and you get both boarding passes","x"],
      ["12:55","AI 1874 departs Kolkata (CCU)","i"],
      ["~15:30","Land in Delhi. Follow the international transfer signs to T3 for emigration and security. That takes most of the layover (time from Air India's schedule, check the app)","x"],
      ["Delhi","1 stop in Delhi (DEL), change to AI 358","i"],
      ["~18:15","AI 358 departs Delhi (time from Air India's schedule, check the app)","x"],
      ["On board","Meals complimentary","i"],
      ["~20:30","After dinner, set your watch to Japan time (+3:30) and sleep. 20:30 in India is midnight in Tokyo","x"],
      ["05:55","Land at Haneda Terminal 3, Tue 20 Oct (Tokyo time)","i"],
    ],
    places: [
    ],
    tips: [["Seats","Your booking shows seats only partly selected. Pick seats together at web check-in, which opens 48 h before."], ["Before you fly","Ask Air India for a vegetarian meal on both flights, at least 24 h ahead. Fill in Visit Japan Web and save the immigration and customs QR codes."], ["Phone","Download offline Google Maps for Tokyo, Kyoto and Osaka, and Japanese in Google Translate. Set up an eSIM or pocket Wi-Fi so it works the moment you land."], ["Transit card","On an iPhone, add a Suica to Apple Wallet before you fly. On Android, buy one at Haneda."]],
    sleep: "On the plane (Delhi → Tokyo)",
  },
  {
    date: "2026-10-20", city: "tokyo", title: "Tokyo arrival, tour and Akihabara", short: "Tokyo arrival, half-day tour",
    gist: "Tokyo Arrival. Tokyo SIC (shared group) half-day tour.",
    timeline: [
      ["05:55","Land at Haneda Terminal 3","i"],
      ["07:00","Private airport transfer to the hotel (about 40 min)","i"],
      ["07:45","Reach the hotel, leave bags at the front desk","x"],
      ["08:00","Breakfast at 7-Eleven","x","seven"],
      ["09:00","Slow walk in Shinjuku Gyoen garden (opens 9 am)","x","gyoen"],
      ["10:45","Optional: free city view from the Tokyo Metropolitan Government Building, or rest in the hotel lobby","x","tmg"],
      ["12:00–13:00","Room ready (earlier if available). Official check-in is 3 pm","i"],
      ["12:15","Lunch","x","ain"],
      ["13:00","Room: shower and a short nap (under 30 min)","x"],
      ["13:40","Leave for the tour pickup point (not confirmed yet)","x"],
      ["14:00","Tour starts (3–4 hours)","i"],
      ["","Imperial Palace Plaza (photo stop)","i"],
      ["","Senso-ji Temple and Nakamise Shopping Street (shopping time, max 1 hour)","i","naka"],
      ["","Goshuin and a goshuincho (stamp book) at Senso-ji. Do this before shopping, the counter closes 16:30","x","gosho"],
      ["","Optional goshuin: Asakusa Shrine, right beside Senso-ji's main hall (office until 16:00)","x","asakusa"],
      ["","Kabukiza (drive-by)","i"],
      ["","National Diet Building (drive-by)","i"],
      ["","Tokyo Tower Main Deck (photo stop)","i"],
      ["~17:30","Tour ends","i"],
      ["17:45","Train to Akihabara, 30–40 min (tour drop-off not confirmed yet)","x","toaki"],
      ["18:15","Mandarake Complex: second-hand figures, manga and anime goods","x","mand"],
      ["19:15","Explore Chuo-dori, the main road: walk along it and go into any shop or arcade that looks good","x","road"],
      ["20:15","Dinner: Indian","x","zeera"],
      ["21:00","Back to the hotel (about 30 min)","x","fromaki"],
      ["22:00","Sleep (Fuji tour starts 08:15)","x"],
    ],
    places: [
      {
        id: "seven",
        t: "08:00",
        type: "Eat",
        name: "7-Eleven Shinjuku 1-chome",
        what: "Convenience store next to the hotel",
        dist: "50 m from the hotel · 1 min",
        hours: "Open 24 hours",
        note: "",
        url: "https://www.google.com/maps/dir/?api=1&origin=Citadines+Shinjuku+Tokyo&origin_place_id=ChIJw3B7QeiMGGARMd-dUShWkFU&destination=7-Eleven+Shinjuku+1-chome&destination_place_id=ChIJDwGrFeiMGGARLCeEfqSx1T0&travelmode=walking",
      },
      {
        id: "gyoen",
        t: "09:00–10:30",
        type: "See",
        name: "Shinjuku Gyoen National Garden",
        what: "Huge, calm garden with ponds and lawns. Easy walk while the room isn't ready",
        dist: "About 700 m from the hotel · 10 min",
        hours: "Tue 9 am–4:30 pm",
        note: "Entry about ¥500",
        url: "https://www.google.com/maps/dir/?api=1&origin=Citadines+Shinjuku+Tokyo&origin_place_id=ChIJw3B7QeiMGGARMd-dUShWkFU&destination=Shinjuku+Gyoen+National+Garden&destination_place_id=ChIJPyOTG8KMGGARh_IXobWxHmo&travelmode=walking",
      },
      {
        id: "tmg",
        t: "10:45 · optional",
        type: "See",
        name: "Tokyo Metropolitan Government Building",
        what: "Free observation deck on the 45th floor, about 200 m up, with a view over all of Tokyo. Mt. Fuji shows on a clear morning",
        dist: "About 10 min by taxi from Shinjuku Gyoen, on the west side of Shinjuku",
        hours: "From 9:30. One of the two decks is sometimes closed, check online",
        note: "Free. Bag check at the entrance. Skip it and rest in the hotel lobby if you're tired",
        url: "https://www.google.com/maps/dir/?api=1&origin=Shinjuku+Gyoen+National+Garden&destination=Tokyo+Metropolitan+Government+Building&travelmode=driving",
      },
      {
        id: "ain",
        t: "12:15",
        type: "Eat",
        name: "Ain Soph Journey",
        what: "Fully vegan cafe: pancakes, set lunches",
        dist: "About 650 m from the hotel · 9 min",
        hours: "Tue lunch until 4 pm",
        note: "Gets busy; book a table online",
        url: "https://www.google.com/maps/dir/?api=1&origin=Citadines+Shinjuku+Tokyo&origin_place_id=ChIJw3B7QeiMGGARMd-dUShWkFU&destination=Ain+Soph+Journey+Shinjuku&destination_place_id=ChIJyUynodyMGGARfdwk4A8pub8&travelmode=walking",
      },
      {
        id: "naka",
        t: "During the tour",
        type: "Shop",
        name: "Nakamise Street",
        what: "Souvenirs: fans, keychains, chopsticks",
        dist: "On the way into Senso-ji",
        hours: "Stalls close around 5 pm",
        note: "Link starts at Senso-ji",
        url: "https://www.google.com/maps/dir/?api=1&origin=Senso-ji+Temple+Asakusa&destination=Nakamise+Shopping+Street&destination_place_id=ChIJPd37MMGOGGARvJ2hfxoiNVE&travelmode=walking",
      },
      {
        id: "gosho",
        t: "During the tour",
        type: "Shop",
        name: "Senso-ji goshuin counter (Yogodo Hall)",
        what: "Temple stamp in your own book. ¥300 each, two designs (¥600 for both). Buy the goshuincho at the temple: about ¥1,500 for a plain one, ¥3,000 to ¥5,000 for fancier covers",
        dist: "About 600 m in from Kaminarimon gate · west of the main hall",
        hours: "Goshuin counter 8:00–16:30",
        note: "Weekday queue can be 10–30 min. If your stop at Senso-ji starts after about 15:45, go here first and skip the shopping. Bring coins. Asakusa Shrine, right beside the main hall, gives a second stamp (¥500, weekday office until 16:00)",
        url: "https://www.google.com/maps/dir/?api=1&origin=Kaminarimon%20Asakusa&destination=Senso-ji%20Temple%20Asakusa&travelmode=walking",
      },
      {
        id: "asakusa",
        t: "During the tour · optional",
        type: "Goshuin",
        name: "Asakusa Shrine",
        what: "Small Shinto shrine right next to Senso-ji. A second stamp from the same stop",
        dist: "Beside the Senso-ji main hall, on its right (east) side",
        hours: "Goshuin office weekdays 9:00–16:00",
        note: "¥500. Only if the tour gives you time after the Senso-ji stamp",
        url: "https://www.google.com/maps/search/?api=1&query=Asakusa%20Shrine%20Tokyo",
      },
      {
        id: "toaki",
        t: "17:45",
        type: "Go",
        name: "Route: to Akihabara",
        what: "Where the tour drops you isn't confirmed, so open this link there: it routes from where you are. From most of central Tokyo it's the JR Yamanote or Keihin-Tohoku line.\nDo not take the orange Chuo Rapid, it skips Akihabara.\nAt Akihabara take the Electric Town Exit.",
        dist: "About 30–40 min",
        hours: "",
        note: "",
        url: "https://www.google.com/maps/dir/?api=1&destination=Akihabara%20Station&travelmode=transit",
      },
      {
        id: "mand",
        t: "18:15–19:15",
        type: "Shop",
        name: "Mandarake Complex",
        what: "Eight floors of second-hand anime goods: figures, manga, cels, trading cards. The best place in Tokyo for collectibles at fair prices",
        dist: "About 470 m from Akihabara Station · 6 min",
        hours: "12:00–20:00",
        note: "Closes first, so go here before anything else. Tax-free with passport",
        url: "https://www.google.com/maps/dir/?api=1&origin=Akihabara%20Station&destination=Mandarake%20Complex%20Akihabara&travelmode=walking",
      },
      {
        id: "road",
        t: "19:15–20:15",
        type: "See",
        name: "Chuo-dori, Akihabara's main road",
        what: "No set stops: walk along the main road and go into whatever looks good. Both sides are lined with anime shops, arcades, retro game shops and electronics stores. Animate (new anime goods) and arcades like Taito Station and GiGO (claw machines, rhythm games, about ¥100 a play) are all along here",
        dist: "Back onto the main road from Mandarake · about 10 min end to end",
        hours: "Most shops close 20:00–21:00, arcades stay open later",
        note: "Before you split up, agree to meet at the Electric Town exit of Akihabara Station in case phones fail",
        url: "https://www.google.com/maps/dir/?api=1&origin=Mandarake%20Complex%20Akihabara&destination=Chuo-dori%20Akihabara&travelmode=walking",
      },
      {
        id: "zeera",
        t: "20:15",
        type: "Eat",
        name: "ZEERA Akihabara",
        what: "Indian restaurant with a vegetarian menu: curries and naan. Seating is in private rooms, so it's quiet after a long day",
        dist: "3 min from Suehirocho Station, at the north end of Chuo-dori",
        hours: "Dinner 15:00–23:00 (last order 22:30) per listings",
        note: "About ¥3,000 a person. Ask for no meat. Fallback: Indian Restaurant Aarti, vegetable curries, 17:00–22:00, cash only",
        url: "https://www.google.com/maps/search/?api=1&query=ZEERA%20Akihabara%20Indian%20restaurant",
      },
      {
        id: "fromaki",
        t: "21:00",
        type: "Go",
        name: "Route: back to the hotel",
        what: "JR Chuo-Sobu Line from Akihabara, 1 stop to Ochanomizu. Change to the Marunouchi Line (M) toward Ogikubo, 10 stops to Shinjuku-gyoemmae (M10). Take Exit 2, then 5 min walk to the hotel.",
        dist: "About 30 min door to door",
        hours: "",
        note: "",
        url: "https://www.google.com/maps/dir/?api=1&origin=Akihabara+Station&destination=Citadines+Shinjuku+Tokyo&destination_place_id=ChIJw3B7QeiMGGARMd-dUShWkFU&travelmode=transit",
      },
    ],
    tips: [["Not confirmed yet","Tour pickup point and where it drops you. The Akihabara evening assumes you're free by about 17:45."], ["If you're fading","Cut the walk along Chuo-dori short. Keep Mandarake and dinner, and you're back by about 21:00."]],
    sleep: "Citadines Shinjuku, Tokyo",
  },
  {
    date: "2026-10-21", city: "tokyo", title: "Mt. Fuji and Hakone", short: "Mt. Fuji and Hakone",
    gist: "Tokyo SIC: Mt. Fuji and Hakone Tour [Return by Shinkansen] With Lunch (From Shinjuku).",
    timeline: [
      ["06:45","Wake up","x"],
      ["07:00","Hotel breakfast","x"],
      ["07:45","Leave for the tour start (starting point to be announced)","x"],
      ["08:15","Tour starts","i"],
      ["","Mt. Fuji 5th Station","i"],
      ["","Optional goshuin: Komitake Shrine, and a Fuji-shaped omamori (charm)","x","komi"],
      ["","Fuji melon bread and 5th-station souvenirs","x","shop5"],
      ["","Lunch (included)","i"],
      ["","Hakone Ropeway","i"],
      ["","Owakudani: black eggs (kuro-tamago), and a look for Evangelion goods","x","kuro"],
      ["","Optional goshuin: Hakone Shrine, only if the tour stops at Lake Ashi","x","hakone"],
      ["","Return by Shinkansen","i"],
      ["20:00","Tour ends at Tokyo Station","i"],
      ["20:05","Tokyo Character Street: Jump Shop, Ghibli and Pokémon shops (they close 20:30)","x","chars"],
      ["20:40","Dinner: vegan ramen inside the station","x","tans"],
      ["21:30","Marunouchi line straight to Shinjuku-gyoemmae (about 20 min)","x","back"],
      ["22:15","Back at the hotel, sleep","x"],
    ],
    places: [
      {
        id: "komi",
        t: "At the 5th Station",
        type: "Goshuin",
        name: "Fujisan Komitake Shrine",
        what: "Small shrine behind the shops. The goshuin shows Mt. Fuji and cherry blossom. The shrine is known for Mt. Fuji-shaped omamori (charms)",
        dist: "A short walk from the shops · exact bus stop not confirmed yet",
        hours: "Shrine office 8:30–16:30",
        note: "Goshuin and charm prices not confirmed. Bring your goshuincho from Senso-ji",
        url: "https://www.google.com/maps/dir/?api=1&origin=Fuji%20Subaru%20Line%205th%20Station&destination=Fujisan%20Komitake%20Shrine&travelmode=walking",
      },
      {
        id: "shop5",
        t: "At the 5th Station",
        type: "Eat",
        name: "Gogoen Rest House and Komitake Shop",
        what: "Mt. Fuji melon bread (the best-known snack here), postcards, wooden charms and Fuji-themed gifts. Coin lockers are on site",
        dist: "Next to the bus stop",
        hours: "",
        note: "Hot melon bread suits the cold. Not confirmed how long the tour stays; ask your guide",
        url: "https://www.google.com/maps/search/?api=1&query=Mt.+Fuji+5th+Station+Gogoen+Rest+House",
      },
      {
        id: "kuro",
        t: "Hakone Ropeway",
        type: "Shop",
        name: "Owakudani Kuro-tamago-kan",
        what: "Black eggs: ordinary eggs boiled in the volcanic springs, the shells turn black. Eat one fresh or buy a pack. Black-egg sweets and cookies also sold. Hakone is the real-life model for Evangelion's Tokyo-3, so check the ropeway shops for Eva goods",
        dist: "At Owakudani ropeway station",
        hours: "Ropeway runs 9:00–17:00 Feb to Nov",
        note: "Eva goods in October 2026 not confirmed. The ropeway stops in strong wind or poor visibility. Which stations your tour uses is not confirmed yet",
        url: "https://www.google.com/maps/dir/?api=1&origin=Owakudani%20Station&destination=Owakudani%20Kurotamago%20Kan&travelmode=walking",
      },
      {
        id: "hakone",
        t: "Hakone · optional",
        type: "Goshuin",
        name: "Hakone Shrine",
        what: "Shrine in the forest on the shore of Lake Ashi, known for its red torii gate standing in the water",
        dist: "Lake Ashi, Moto-Hakone side · only works if your tour goes there",
        hours: "Stamp hours not confirmed",
        note: "Price not confirmed. Ask your guide in the morning whether the tour stops at Lake Ashi and for how long",
        url: "https://www.google.com/maps/search/?api=1&query=Hakone%20Shrine",
      },
      {
        id: "chars",
        t: "20:05–20:30",
        type: "Shop",
        name: "Tokyo Character Street",
        what: "About 30 character shops: Jump Shop (One Piece, Naruto, Dragon Ball), Ghibli's Donguri, Pokémon, Kamen Rider",
        dist: "Underground on the Yaesu side of Tokyo Station · exact meeting point not confirmed",
        hours: "10:00–20:30",
        note: "Only if the tour ends on time. If it runs late, go straight to dinner, T's Tantan is open until 10 pm",
        url: "https://www.google.com/maps/search/?api=1&query=Tokyo%20Character%20Street%20Tokyo%20Station",
      },
      {
        id: "tans",
        t: "20:40",
        type: "Eat",
        name: "T's Tantan",
        what: "Fully vegan ramen and gyoza",
        dist: "Inside Tokyo Station, Gransta B1F, outside the ticket gates",
        hours: "Until 10 pm",
        note: "Hard to find; ask staff for \"Gransta B1\"",
        url: "https://www.google.com/maps/dir/?api=1&origin=Citadines+Shinjuku+Tokyo&origin_place_id=ChIJw3B7QeiMGGARMd-dUShWkFU&destination=T%27s+Tantan+Tokyo+Station&destination_place_id=ChIJtTLL9fuLGGARm6IP54k3xn4&travelmode=transit",
      },
      {
        id: "back",
        t: "21:30",
        type: "Go",
        name: "Route back to the hotel",
        what: "Marunouchi Line (M17 Tokyo) toward Ogikubo, no change. 7 stops to Shinjuku-gyoemmae (M10). Take Exit 2, then 5 min walk to the hotel.",
        dist: "About 20–25 min door to door",
        hours: "",
        note: "",
        url: "https://www.google.com/maps/dir/?api=1&origin=T%27s+Tantan+Tokyo+Station&origin_place_id=ChIJtTLL9fuLGGARm6IP54k3xn4&destination=Citadines+Shinjuku+Tokyo&destination_place_id=ChIJw3B7QeiMGGARMd-dUShWkFU&travelmode=transit",
      },
    ],
    tips: [["Not confirmed yet","Tour starting point and how long you get at the 5th Station."], ["Goshuin today","Komitake Shrine at the 5th Station (office 8:30–16:30). If the tour also stops at Lake Ashi, Hakone Shrine there gives one too, so ask your guide. Shrines are shut by the time you're back in Tokyo."], ["Dress warm","October at the 5th Station averages about 1 to 9 °C. Wear a thick jacket, hat and gloves."], ["Dashi at lunch","Ask the agent for a vegetarian set lunch and say no dashi or fish stock. The tour lunch is included, so request it before the day."]],
    sleep: "Citadines Shinjuku, Tokyo",
  },
  {
    date: "2026-10-22", city: "tokyo", title: "Tokyo Disneyland", short: "Tokyo Disneyland",
    gist: "Tokyo – Disney transfer (two way, private). Disneyland entry ticket only, with transfers.",
    timeline: [
      ["07:00","Wake up","x"],
      ["07:30","Hotel breakfast","x"],
      ["08:15","Private transfer to Disneyland (pickup time to confirm)","i"],
      ["09:00","Tokyo Disneyland (entry ticket included). Check park hours for the day","i"],
      ["09:15","Rides first, while the queues are short: Big Thunder Mountain (coaster)","x","thunder"],
      ["10:15","Shootin' Gallery (paid, barely any queue)","x","shoot"],
      ["10:30","Splash Mountain (log flume with a big drop)","x","splash"],
      ["11:30","Pirates of the Caribbean","x","pirates"],
      ["12:30","Lunch","x","food"],
      ["13:30","Wander World Bazaar and the shops, snacks along the way","x","snacks"],
      ["14:30","Star Tours (Star Wars 3D simulator)","x","startours"],
      ["15:15","Buzz Lightyear's Astro Blasters (shooting ride, score points)","x","buzz"],
      ["16:00","Haunted Mansion, Halloween version","x","mansion"],
      ["Afternoon","Halloween parade (check the app for the time)","x","parade"],
      ["","Bonus if queues are short: Gadget's Go Coaster, Beauty and the Beast","x"],
      ["17:00","Souvenir shopping, at the end so you're not carrying bags all day","x","shop"],
      ["18:00","Dinner in the park","x","food"],
      ["19:30","Private transfer back to the hotel (time to confirm)","i"],
      ["20:30","Back at the hotel. Pack: you check out tomorrow at 07:45","x"],
      ["21:30","Optional: 20 min walk to see the 3D cat and the Godzilla head","x","cat"],
      ["22:30","Sleep","x"],
    ],
    places: [
      {
        id: "thunder",
        t: "09:15",
        type: "Ride",
        name: "Big Thunder Mountain",
        what: "Runaway mine-train roller coaster through a desert mountain: fast turns and small drops, no loops",
        dist: "Westernland",
        hours: "Head here first after the gate opens",
        note: "Typical wait 40–70 min later in the day",
        url: "https://www.google.com/maps/dir/?api=1&origin=Tokyo%20Disneyland&destination=Big%20Thunder%20Mountain%20Tokyo%20Disneyland&travelmode=walking",
      },
      {
        id: "shoot",
        t: "10:15",
        type: "Game",
        name: "Westernland Shootin' Gallery",
        what: "Wild West shooting range: rifles fire light beams at targets in an old frontier town, and the targets react when you hit them",
        dist: "Westernland, between Big Thunder and Splash Mountain",
        hours: "",
        note: "Paid separately, a few hundred yen a round. Barely any queue",
        url: "https://www.google.com/maps/dir/?api=1&origin=Tokyo%20Disneyland&destination=Westernland%20Shootin'%20Gallery%20Tokyo%20Disneyland&travelmode=walking",
      },
      {
        id: "splash",
        t: "10:30",
        type: "Ride",
        name: "Splash Mountain",
        what: "Log flume through animal scenes, ending in a big drop",
        dist: "Critter Country, next to Westernland",
        hours: "",
        note: "You will get wet, so a cheap poncho helps in October. A single rider line can be much faster if it's open",
        url: "https://www.google.com/maps/dir/?api=1&origin=Tokyo%20Disneyland&destination=Splash%20Mountain%20Tokyo%20Disneyland&travelmode=walking",
      },
      {
        id: "pirates",
        t: "11:30",
        type: "Ride",
        name: "Pirates of the Caribbean",
        what: "Boat ride through pirate battles and treasure caves, with one small drop in the dark",
        dist: "Adventureland",
        hours: "",
        note: "Big boats keep the queue moving. Typical wait 10–30 min",
        url: "https://www.google.com/maps/dir/?api=1&origin=Tokyo%20Disneyland&destination=Pirates%20of%20the%20Caribbean%20Tokyo%20Disneyland&travelmode=walking",
      },
      {
        id: "food",
        t: "12:30 and 18:00",
        type: "Eat",
        name: "Vegetarian food in the park",
        what: "Restaurant Hokusai: vegetable tempura set, about ¥2,700 (Japanese).\nEastside Cafe: tomato spaghetti and mushroom soup, book ahead.\nGrandma Sara's Kitchen: plant-based dry curry doria (baked curry rice), about ¥1,500.\nGrilled vegetable pizza and churros at snack stands.",
        dist: "Hokusai and Eastside Cafe are in World Bazaar near the entrance. Grandma Sara's is in Critter Country",
        hours: "",
        note: "Menus change, so check the Tokyo Disney Resort app. Budget about ¥5,000–8,000 per person for food over the day",
        url: "https://www.google.com/maps/dir/?api=1&origin=Tokyo%20Disneyland&destination=Restaurant%20Hokusai%20Tokyo%20Disneyland&travelmode=walking",
      },
      {
        id: "snacks",
        t: "13:30",
        type: "Shop",
        name: "World Bazaar, popcorn and snacks",
        what: "The covered entrance street: shops, photo spots, Halloween decorations. Tokyo is known for its popcorn flavours (curry, soy-sauce butter, milk tea, caramel), each sold at a different stand, and for collectible popcorn buckets, with Halloween designs in October. Also Little Green Men mochi in Tomorrowland and flavoured churros",
        dist: "From the entrance up to the castle",
        hours: "",
        note: "Popcorn box about ¥400–600, bucket with popcorn ¥2,500–3,800, churro or mochi ¥500–700",
        url: "https://www.google.com/maps/dir/?api=1&origin=Tokyo%20Disneyland&destination=World%20Bazaar%20Tokyo%20Disneyland&travelmode=walking",
      },
      {
        id: "startours",
        t: "14:30",
        type: "Ride",
        name: "Star Tours: The Adventures Continue",
        what: "3D motion simulator through Star Wars scenes. The route changes each time, so a second ride is different",
        dist: "Tomorrowland",
        hours: "",
        note: "Bumpy. The shop next to it sells Star Wars goods; which items isn't confirmed",
        url: "https://www.google.com/maps/dir/?api=1&origin=Tokyo%20Disneyland&destination=Star%20Tours%20Tokyo%20Disneyland&travelmode=walking",
      },
      {
        id: "buzz",
        t: "15:15",
        type: "Ride",
        name: "Buzz Lightyear's Astro Blasters",
        what: "Ride a spinning car and shoot targets with a laser blaster. Your score shows at the end, so compete",
        dist: "Tomorrowland",
        hours: "",
        note: "Typical wait 20–45 min",
        url: "https://www.google.com/maps/dir/?api=1&origin=Tokyo%20Disneyland&destination=Buzz%20Lightyear's%20Astro%20Blasters%20Tokyo%20Disneyland&travelmode=walking",
      },
      {
        id: "mansion",
        t: "16:00",
        type: "Ride",
        name: "Haunted Mansion Holiday Nightmare",
        what: "Spooky dark ride through a haunted house. From mid-September to Halloween it's redone with The Nightmare Before Christmas theme",
        dist: "Fantasyland, near the castle",
        hours: "",
        note: "Typical wait 40–70 min",
        url: "https://www.google.com/maps/dir/?api=1&origin=Tokyo%20Disneyland&destination=Haunted%20Mansion%20Tokyo%20Disneyland&travelmode=walking",
      },
      {
        id: "parade",
        t: "Afternoon",
        type: "See",
        name: "Disney Halloween parade",
        what: "Disney Halloween runs 16 Sep–31 Oct. The villains' Halloween parade runs once a day, about 45 min",
        dist: "Along the parade route through the park",
        hours: "Time not confirmed, check the app",
        note: "Arrive 30 min early for a spot. Queues drop while it runs, so it's also a good time for a ride",
        url: "https://www.google.com/maps/dir/?api=1&origin=Tokyo%20Disneyland&destination=Tokyo%20Disneyland%20Parade%20Route&travelmode=walking",
      },
      {
        id: "shop",
        t: "17:00",
        type: "Shop",
        name: "Souvenirs",
        what: "Ears headband about ¥2,000–2,500, T-shirt ¥3,000–4,500, plush ¥2,500–5,000+, keychain ¥1,000–1,500, cookie or chocolate tin ¥1,500–2,500. The biggest shops are in World Bazaar, by the exit",
        dist: "World Bazaar",
        hours: "",
        note: "Prices from recent years. No build-your-own lightsaber here; Akihabara toy shops are better for proper Star Wars gear",
        url: "https://www.google.com/maps/dir/?api=1&origin=Tokyo%20Disneyland&destination=World%20Bazaar%20Tokyo%20Disneyland&travelmode=walking",
      },
      {
        id: "cat",
        t: "21:30 · optional",
        type: "See",
        name: "Shinjuku 3D Cat and Godzilla Head",
        what: "The giant 3D cat on the billboard above the East Exit plaza plays every 15 min. Then the Godzilla head on Hotel Gracery in Kabukicho, lit at night. It roars on the hour 12:00–20:00, so you miss the roar",
        dist: "Cat to Godzilla about 430 m · 6 min",
        hours: "Cat 07:00–01:00",
        note: "Skip it if you're tired. Stay on the main road in Kabukicho and ignore people calling you into bars. Metro home: Shinjuku to Shinjuku-gyoemmae, 2 stops",
        url: "https://www.google.com/maps/dir/?api=1&origin=Shinjuku-sanchome%20Station&destination=Cross%20Shinjuku%20Vision&travelmode=walking",
      },
    ],
    tips: [["Ask the agent","Pickup and return times for the Disney transfer."], ["Beat the queues","Be at the gate before it opens and go straight to Big Thunder. If a queue is huge, Premier Access in the app skips it for about ¥1,500–2,500 a ride."], ["Space Mountain","Closed for a rebuild until about 2027."], ["No goshuin today","You're in the park while shrine offices are open."]],
    sleep: "Citadines Shinjuku, Tokyo",
  },
  {
    date: "2026-10-23", city: "kyoto", title: "teamLab and bullet train to Kyoto", short: "Bullet train to Kyoto",
    gist: "teamLab in the morning, then the 4 pm bullet train to Kyoto.",
    timeline: [
      ["06:45","Wake up","x"],
      ["07:10","Hotel breakfast","x"],
      ["07:45","Check out from the hotel. Leave bags at the front desk","i"],
      ["07:55","Taxi to teamLab (15–20 min), or metro about 25 min","x","rtl"],
      ["08:30–11:00","teamLab (Tokyo), 2–3 hours","i","bl"],
      ["11:00","Taxi to Shibuya (about 15 min)","x"],
      ["11:15","Shibuya Scramble Crossing","x","cross"],
      ["11:20","Shops around the crossing: Center Gai, Shibuya 109, MEGA Don Quijote, ABC-Mart (shoes)","x","shibuya"],
      ["12:00","MIYASHITA PARK, then walk Cat Street to Omotesando: sneaker and streetwear shops all the way","x","catst"],
      ["12:45","Lunch, option 1: Indian near Omotesando Station","x","gonguru"],
      ["","Lunch, option 2: vegan burgers or curry at the end of the route, by Harajuku Station","x","jang"],
      ["13:25","Omotesando avenue and Takeshita Street, ending at Harajuku Station","x","takeshita"],
      ["","Optional goshuin: Meiji Jingu, next to Harajuku Station, only if you're ahead of time (about 40 min)","x","meiji"],
      ["13:50","Metro back to the hotel (about 25 min)","x","back23"],
      ["14:15","Collect bags at the front desk","x"],
      ["14:30","Station transfer (private)","i"],
      ["16:00","Bullet train to Kyoto (tickets included)","i"],
      ["~18:15","Arrive at Kyoto Station","x"],
      ["18:30","Check in at the Kyoto hotel","i"],
      ["19:15","Dinner: Japanese curry rice","x","coco"],
      ["20:30","Kyoto Station at night: the lit-up Great Stairway and the free Sky Garden","x","stairs"],
      ["22:00","Sleep (tour pickup 08:00–08:30)","x"],
    ],
    places: [
      {
        id: "rtl",
        t: "07:55",
        type: "Go",
        name: "Route: hotel to teamLab",
        what: "Taxi: 15–20 min.\nMetro: Marunouchi Line (M) from Shinjuku-gyoemmae toward Ikebukuro, 2 stops to Yotsuya (M12). Change to the Namboku Line (N) toward Meguro, 3 stops to Roppongi-itchome (N05). Take Exit 1 and follow the signs into Azabudai Hills.",
        dist: "About 25 min by metro, door to door",
        hours: "",
        note: "Bags stay at the hotel front desk",
        url: "https://www.google.com/maps/dir/?api=1&origin=Citadines+Shinjuku+Tokyo&origin_place_id=ChIJw3B7QeiMGGARMd-dUShWkFU&destination=teamLab+Borderless+Azabudai+Hills&destination_place_id=ChIJQ5Sa1PqJGGARUSaNKKOrMVg&travelmode=transit",
      },
      {
        id: "bl",
        t: "08:30–11:00",
        type: "See",
        name: "teamLab Borderless",
        what: "Digital art museum, rooms of light and sound",
        dist: "About 5 km from the hotel · taxi 15–20 min",
        hours: "Opens 8:30 am",
        note: "Book the 8:30 entry in advance and check the time on your ticket. Free lockers inside",
        url: "https://www.google.com/maps/dir/?api=1&origin=Citadines+Shinjuku+Tokyo&origin_place_id=ChIJw3B7QeiMGGARMd-dUShWkFU&destination=teamLab+Borderless+Azabudai+Hills&destination_place_id=ChIJQ5Sa1PqJGGARUSaNKKOrMVg&travelmode=transit",
      },
      {
        id: "cross",
        t: "11:15",
        type: "See",
        name: "Shibuya Scramble Crossing",
        what: "The world-famous crossing: wait for the green light and cross with the crowd",
        dist: "About 4 km from teamLab · taxi 15 min",
        hours: "",
        note: "Start of the walking route. Everything after this is on foot until Harajuku Station, about 2 km in all",
        url: "https://www.google.com/maps/dir/?api=1&origin=teamLab+Borderless+Azabudai+Hills&origin_place_id=ChIJQ5Sa1PqJGGARUSaNKKOrMVg&destination=Shibuya+Scramble+Crossing&destination_place_id=ChIJK9EM68qLGGARacmu4KJj5SA&travelmode=driving",
      },
      {
        id: "shibuya",
        t: "11:20–12:00",
        type: "Shop",
        name: "Shops around the crossing",
        what: "Center Gai: pedestrian street full of shops and cafes.\nShibuya 109: young fashion.\nMEGA Don Quijote: huge discount store packed with snacks, cosmetics, gadgets and souvenirs, open 24 hours.\nABC-Mart Grand Stage: four floors of sneakers, including Japan-only models.",
        dist: "All 2–5 min from the crossing",
        hours: "Most shops open 10:00–11:00",
        note: "Bring passports: most big shops take 10% tax off at the till. Japanese shoe sizes run small, so try them on",
        url: "https://www.google.com/maps/dir/?api=1&origin=Shibuya%20Scramble%20Crossing&destination=MEGA%20Don%20Quijote%20Shibuya&travelmode=walking",
      },
      {
        id: "catst",
        t: "12:00–12:45",
        type: "Shop",
        name: "MIYASHITA PARK and Cat Street",
        what: "MIYASHITA PARK: a long mall with a park on its roof, full of streetwear brands. Cat Street starts beside it and runs north to Omotesando: a quiet lane of sneaker, streetwear and vintage shops",
        dist: "MIYASHITA PARK is 5–7 min from the crossing. Cat Street is about 15 min end to end",
        hours: "Most shops from 11:00",
        note: "If your parents get tired, Shibuya to Harajuku is 1 stop on the JR Yamanote line, or a short taxi",
        url: "https://www.google.com/maps/dir/?api=1&origin=MIYASHITA%20PARK&destination=Cat%20Street%20Harajuku&travelmode=walking",
      },
      {
        id: "gonguru",
        t: "12:45 · option 1",
        type: "Eat",
        name: "Gonguru, Minami-Aoyama",
        what: "Indian restaurant with vegetarian options",
        dist: "About 2 min from Omotesando Station, a few minutes off Omotesando avenue where Cat Street comes out",
        hours: "Lunch hours not confirmed, check before",
        note: "Well rated on Tabelog (3.49). Ask for no meat",
        url: "https://www.google.com/maps/search/?api=1&query=Gonguru%20Minami%20Aoyama",
      },
      {
        id: "jang",
        t: "Option 2",
        type: "Eat",
        name: "Vegan Bistro Jangara",
        what: "Fully vegan: burgers, Japanese curry and gyoza, so everything is safe for vegetarians. Rated 4.7",
        dist: "Opposite Harajuku Station (2F, above FamilyMart), at the end of the route",
        hours: "11:00–21:00",
        note: "No detour: eat here last, then take the metro",
        url: "https://www.google.com/maps/search/?api=1&query=Vegan%20Bistro%20Jangara%20Harajuku",
      },
      {
        id: "takeshita",
        t: "13:25",
        type: "Shop",
        name: "Omotesando and Takeshita Street",
        what: "Omotesando: wide tree-lined avenue of big brands and Omotesando Hills mall. Takeshita Street: a narrow, crowded lane of quirky fashion shops and crepe stands that ends at Harajuku Station",
        dist: "About 5–10 min walk",
        hours: "",
        note: "Busy at midday. Crepes about ¥500–800. Skip it if you're short of time",
        url: "https://www.google.com/maps/dir/?api=1&origin=Omotesando%20Hills&destination=Takeshita%20Street%20Harajuku&travelmode=walking",
      },
      {
        id: "meiji",
        t: "Optional",
        type: "Goshuin",
        name: "Meiji Jingu",
        what: "Big forest shrine next to Harajuku Station. Goshuin ¥500 at Nagado Hall",
        dist: "1 min from Harajuku Station to the gate · the office is a longer walk into the grounds",
        hours: "Office roughly 8:00–16:30",
        note: "Needs about 40 minutes. Only if you're ahead of time",
        url: "https://www.google.com/maps/search/?api=1&query=Meiji%20Jingu",
      },
      {
        id: "back23",
        t: "13:50",
        type: "Go",
        name: "Route back to the hotel",
        what: "Walk 5 min to Meiji-jingumae <Harajuku> Station. Fukutoshin Line (F15) toward Ikebukuro, 2 stops (Kita-sando) to Shinjuku-sanchome (F13). Take Exit C7, then 7 min walk to the hotel.\nOr JR Yamanote Line from Harajuku, 2 stops to Shinjuku, then Marunouchi Line 2 stops to Shinjuku-gyoemmae.",
        dist: "About 25 min door to door",
        hours: "",
        note: "Be back by 14:15 for the bags. A taxi is about 15 min",
        url: "https://www.google.com/maps/dir/?api=1&origin=Harajuku+Station&destination=Citadines+Shinjuku+Tokyo&destination_place_id=ChIJw3B7QeiMGGARMd-dUShWkFU&travelmode=transit",
      },
      {
        id: "coco",
        t: "19:15",
        type: "Eat",
        name: "CoCo Ichibanya, Hachijo exit",
        what: "Japanese curry rice, the classic local version: thick, mild and slightly sweet. Ask for the separate vegetarian menu (eggplant, spinach, mushroom, tomato and more). You choose the spice level and how much rice",
        dist: "At the Hachijo (south) exit of Kyoto Station, 2–3 min from the hotel",
        hours: "Listed 11:00–23:45",
        note: "About ¥800–1,200. The vegetarian choice may be limited at this branch. Backup: VEGE DELI Kanna, fully vegetarian curry rice, in the food hall under Kyoto Tower",
        url: "https://www.google.com/maps/search/?api=1&query=CoCo%20Ichibanya%20Minami-ku%20Hachijo%20Entrance%20Kyoto",
      },
      {
        id: "stairs",
        t: "20:30",
        type: "See",
        name: "Kyoto Station Building: stairway and Sky Garden",
        what: "The Great Stairway is lit with LED patterns from the 3rd to 8th floor. The Sky Garden on 15F is a free rooftop with a night view of Kyoto Tower",
        dist: "Inside Kyoto Station, about 5 min from the hotel through the Hachijo (south) exit",
        hours: "Stairway lights 17:00–22:00 · Sky Garden 06:00–23:00",
        note: "Free. The 11F Skyway is free until 22:00 too",
        url: "https://www.google.com/maps/dir/?api=1&origin=Miyako+Hotel+Kyoto+Hachijo&destination=Kyoto+Station+Building&travelmode=walking",
      },
    ],
    tips: [["Package note","Intercity baggage transfer is not included."], ["Be back by 2:30 pm","For the station transfer. The shopping walk is tight: if you're running late, skip Takeshita Street or take a taxi back."], ["Kyoto hotel","Miyako Hotel Kyoto Hachijo is 2 minutes from the Hachijo (south) exit of Kyoto Station. Check-in is from 14:00."]],
    sleep: "Miyako Hotel Kyoto Hachijo",
  },
  {
    date: "2026-10-24", city: "kyoto", title: "Nara, Fushimi Inari, Arashiyama", short: "Nara, Fushimi Inari, Arashiyama",
    gist: "Nara, Fushimi Inari Taisha, Arashiyama bus tour.",
    timeline: [
      ["06:30","Wake up","x"],
      ["07:00","Hotel breakfast","x"],
      ["07:45","Ready in the lobby","x"],
      ["08:00–08:30","Tour starts","i"],
      ["","Nara","i"],
      ["","Fushimi Inari Taisha","i"],
      ["","Goshuin if the tour stops long enough: Fushimi Inari and Todai-ji","x","gosho2"],
      ["","Arashiyama","i"],
      ["Evening","Tour ends (end time not given)","i"],
      ["After tour","Rest at the hotel for an hour","x"],
      ["19:30","Dinner: vegan ramen","x","uzu"],
      ["20:45","Night walk through Pontocho, then the subway home","x","ponto"],
      ["22:30","Back at the hotel, pack","x"],
      ["23:00","Sleep","x"],
    ],
    places: [
      {
        id: "gosho2",
        t: "On the tour",
        type: "Shop",
        name: "Goshuin stops: Fushimi Inari, Todai-ji and others",
        what: "Fushimi Inari goshuin ¥500. Todai-ji ¥300 each. Kasuga Taisha ¥500 and Tenryu-ji in Arashiyama also give stamps if the bus stops there. All go in the goshuincho you buy at Senso-ji on 20 Oct",
        dist: "On the tour route · which Nara sights are visited is not confirmed yet",
        hours: "Fushimi Inari office 8:30–16:30 · Todai-ji Great Buddha Hall 7:30–17:30, other halls 8:30–16:00 · Kasuga Taisha 6:30–17:30 · Tenryu-ji stamps 9:00–16:30",
        note: "If the tour reaches Fushimi Inari after 16:30, the office is closed. Ask your guide when you'll be there",
        url: "https://www.google.com/maps/dir/?api=1&origin=Fushimi%20Inari%20Taisha&destination=Fushimi%20Inari%20Taisha%20Shamusho&travelmode=walking",
      },
      {
        id: "uzu",
        t: "19:30",
        type: "Eat",
        name: "Vegan Ramen UZU Kyoto",
        what: "Fully vegan ramen, so no fish stock. The best-known vegan ramen shop in Kyoto",
        dist: "About 30 min from the hotel. Walk through Kyoto Station to the Karasuma Line, 3 stops to Karasuma-Oike (K08), then 14 min walk. Or change there to the Tozai Line, 1 stop east to Kyoto-Shiyakusho-mae, then 6 min walk",
        hours: "12:00–14:45 and 17:30–22:00 (last order 21:00)",
        note: "Closed on irregular days. Check their Instagram on the day. Fallback if closed: CoCo Ichibanya Hachijo Entrance, near the south exit of Kyoto Station, vegetarian menu",
        url: "https://www.google.com/maps/dir/?api=1&origin=Miyako+Hotel+Kyoto+Hachijo&destination=Vegan%20Ramen%20UZU%20Kyoto&travelmode=transit",
      },
      {
        id: "ponto",
        t: "20:45",
        type: "See",
        name: "Pontocho Alley",
        what: "Narrow stone lane with paper lanterns and old teahouses, best after dark. Walk it south to Shijo Street",
        dist: "About 1.3 km from UZU · 16 min. Shijo Station is 350 m further",
        hours: "Public lane, open all night",
        note: "Most restaurants here serve fish stock, so just walk. Home: Karasuma Line from Shijo (K09), 2 stops to Kyoto Station",
        url: "https://www.google.com/maps/dir/?api=1&origin=Vegan%20Ramen%20UZU%20Kyoto&destination=Pontocho%20Alley%20Kyoto&travelmode=walking",
      },
    ],
    tips: [["Not confirmed yet","Tour end time, and which Nara sights the bus visits. The dinner plan works if the tour ends by about 18:30."], ["Comfortable shoes","Lots of walking at Fushimi Inari."]],
    sleep: "Miyako Hotel Kyoto Hachijo",
  },
  {
    date: "2026-10-25", city: "osaka", title: "Kyoto to Osaka, manga museum and Den Den Town", short: "Bullet train to Osaka",
    gist: "Kyoto to Osaka by bullet train.",
    timeline: [
      ["07:30","Wake up (slower morning)","x"],
      ["08:00","Hotel breakfast","x"],
      ["09:00","Check out. Ask the front desk to hold your bags until noon","x"],
      ["09:30","Taxi to Nishiki Market (about 15 min)","x","rkm"],
      ["10:00","Nishiki Market: tofu doughnuts, pickles, soy milk, and a goshuin at Nishiki Tenmangu","x","nishiki"],
      ["10:40","Taxi to the Manga Museum (about 5 min)","x"],
      ["10:50–11:30","Kyoto International Manga Museum","x","manga"],
      ["11:35","Taxi back to the hotel for the bags","x"],
      ["12:00","Walk to Kyoto Station with the bags (about 5 min)","x"],
      ["12:30","Bullet train to Osaka (ticket and time not confirmed yet)","x"],
      ["~12:50","Arrive Shin-Osaka, Midosuji line to Hommachi (about 15 min)","x","rto"],
      ["13:25","Drop bags at the Osaka hotel","x"],
      ["13:35","Lunch","x","coco_o"],
      ["14:15","Walk to the metro, Midosuji line to Shinsaibashi (1 stop)","x","rpk"],
      ["14:30","Pokémon Center","x","pkm"],
      ["15:15","Jump Shop and Donguri Republic at Shinsaibashi PARCO","x","parcoo"],
      ["16:00","Shoes at Asics, and a shirt from GU or Graniph","x","asics"],
      ["16:25","Taxi to Den Den Town (about 8 min)","x","rden"],
      ["16:40","Anime and retro games in Den Den Town","x","den"],
      ["18:30","Dinner: okonomiyaki","x","chibo"],
      ["19:30","Glico sign photo","x","ebisu"],
      ["19:45","River cruise","x","tombori"],
      ["20:15","Lantern lane","x","hozen"],
      ["20:30","Dessert: taiyaki","x","naruto"],
      ["20:50","Metro Namba → Hommachi (2 stops)","x","rhome"],
      ["21:15","Back at the hotel, rest","x"],
      ["22:45","Sleep","x"],
    ],
    places: [
      {
        id: "rkm",
        t: "09:30",
        type: "Go",
        name: "Route: hotel to Nishiki Market and the Manga Museum",
        what: "Taxi to Nishiki Market, about 15 min (¥1,500). After the market, taxi to the museum, about 5 min (¥700).\nOr by metro: Karasuma Line (K11 Kyoto) toward Kokusaikaikan, 2 stops to Shijo (K09) for the market. Then 1 more stop to Karasuma-Oike (K08), Exit 2, for the museum, about 130 m away.",
        dist: "About 30 min door to door",
        hours: "",
        note: "",
        url: "https://www.google.com/maps/dir/?api=1&origin=Miyako+Hotel+Kyoto+Hachijo&destination=Kyoto%20International%20Manga%20Museum&travelmode=transit",
      },
      {
        id: "nishiki",
        t: "10:00",
        type: "Eat",
        name: "Nishiki Market",
        what: "Kyoto's five-block food street: tofu doughnuts, soy-milk sweets, pickles, fresh tea. Many stalls sell fish, so look for the tofu and vegetable ones",
        dist: "About 15 min by taxi from the hotel (about ¥1,500), then a short walk along the street",
        hours: "About 10:00–18:00, some stalls open earlier",
        note: "Taxi to the Takakura end of the street, then walk east. The street ends at Nishiki Tenmangu, a small shrine that gives goshuin (open 8:00–20:00). Skip the fish skewers",
        url: "https://www.google.com/maps/dir/?api=1&origin=Miyako%20Hotel%20Kyoto%20Hachijo&destination=Nishiki%20Market&travelmode=driving",
      },
      {
        id: "toji",
        t: "Also",
        type: "See",
        name: "Toji goshuin",
        what: "Temple with Japan's tallest wooden pagoda. Goshuin price varies by design, check the board",
        dist: "Near the Kyoto hotel in Minami-ku · a short taxi, check in Maps",
        hours: "8:00–17:00 · halls ¥800",
        note: "Optional early start: breakfast by 07:30, leave 08:15, back for check-out at 09:00",
        url: "https://www.google.com/maps/search/?api=1&query=Toji%20Temple%20Kyoto",
      },
      {
        id: "manga",
        t: "10:50–11:30",
        type: "See",
        name: "Kyoto International Manga Museum",
        what: "The Wall of Manga: about 50,000 manga on open shelves that you can pull down and read. Plus exhibitions, a museum shop with about 3,000 items and a cafe. A former school building",
        dist: "About 130 m from Karasuma-Oike Station",
        hours: "10:00–17:00, last entry 16:30. Closed Wednesdays, open on Sun 25 Oct",
        note: "Admission about ¥1,200 for adults, check at the door. Replaces the Higashi Hongan-ji walk",
        url: "https://www.google.com/maps/dir/?api=1&origin=Karasuma-Oike%20Station&destination=Kyoto%20International%20Manga%20Museum&travelmode=walking",
      },
      {
        id: "rto",
        t: "~12:50",
        type: "Go",
        name: "Route: Shin-Osaka to the hotel",
        what: "Midosuji Line (M13 Shin-Osaka) toward Namba, 5 stops to Hommachi (M18), about 12 min. Take Exit 4, the hotel is 2 min away. Exit 5 is closed after 9 pm and on weekends.",
        dist: "About 15 min plus walking",
        hours: "",
        note: "Midosuji is the red line",
        url: "https://www.google.com/maps/dir/?api=1&origin=Shin-Osaka%20Station&destination=Osaka%20View%20Hotel%20Honmachi&travelmode=transit",
      },
      {
        id: "coco_o",
        t: "13:35",
        type: "Eat",
        name: "CoCo Ichibanya Honmachi 4-chome",
        what: "Quick curry rice lunch. The only CoCo on the trip",
        dist: "About 110 m from the Osaka hotel",
        hours: "Until 10 pm",
        note: "Ask for the vegetarian menu",
        url: "https://www.google.com/maps/dir/?api=1&origin=Osaka+View+Hotel+Honmachi&origin_place_id=ChIJDYCo9OLmAGARHahlNEJ5nhQ&destination=CoCo+Ichibanya+Honmachi+4-chome&destination_place_id=ChIJ_UBzl-LmAGAROd5c6aTbeDg&travelmode=walking",
      },
      {
        id: "rpk",
        t: "14:15",
        type: "Go",
        name: "Route: hotel to Pokémon Center",
        what: "Hommachi Exit 4, Midosuji Line (M18) toward Namba, 1 stop to Shinsaibashi (M19), about 2 min. Follow the signs into Daimaru department store and take the lift to 9F.\nOr walk, about 1.2 km, 16 min.",
        dist: "About 10 min door to door",
        hours: "",
        note: "",
        url: "https://www.google.com/maps/dir/?api=1&origin=Osaka+View+Hotel+Honmachi&origin_place_id=ChIJDYCo9OLmAGARHahlNEJ5nhQ&destination=Pokemon%20Center%20Osaka%20DX&travelmode=transit",
      },
      {
        id: "pkm",
        t: "14:30",
        type: "Shop",
        name: "Pokémon Center Osaka DX",
        what: "Osaka-only pins, cards, plushies. The Pokémon Cafe is next door, but needs a reservation",
        dist: "Daimaru Shinsaibashi 9F · about 1.2 km, or 1 metro stop",
        hours: "10:00–20:00",
        note: "This is the only Pokémon Center on the plan",
        url: "https://www.google.com/maps/dir/?api=1&origin=Osaka+View+Hotel+Honmachi&origin_place_id=ChIJDYCo9OLmAGARHahlNEJ5nhQ&destination=Pokemon+Center+Osaka+DX&destination_place_id=ChIJiZ8OQInnAGART2BGEGqySKk&travelmode=walking",
      },
      {
        id: "parcoo",
        t: "15:15",
        type: "Shop",
        name: "Shinsaibashi PARCO 6F",
        what: "One floor of character shops: Jump Shop (One Piece, Jujutsu Kaisen, Naruto), Donguri Republic (Ghibli), Chiikawa, Pop Mart and the Godzilla Store",
        dist: "A few minutes' walk from the Pokémon Center (confirm in Maps)",
        hours: "About 10:00–20:00, check",
        note: "Jump Shop tees about ¥3,500–4,500. Keep it to 40 minutes",
        url: "https://www.google.com/maps/dir/?api=1&origin=Pokemon%20Center%20Osaka%20DX&destination=Shinsaibashi%20PARCO&travelmode=walking",
      },
      {
        id: "asics",
        t: "16:00",
        type: "Shop",
        name: "Asics Shinsaibashi",
        what: "Japanese running and lifestyle shoes. The GEL-1130 is about ¥14,300. A GU, Graniph or Right-on for a shirt is within about 600 m",
        dist: "About 100 m across the arcade",
        hours: "Until 8 pm",
        note: "Skip the shoes if you already bought a pair in Shibuya. Keep it to 25 min",
        url: "https://www.google.com/maps/dir/?api=1&origin=Pokemon+Center+Osaka+DX&origin_place_id=ChIJiZ8OQInnAGART2BGEGqySKk&destination=asics+Osaka+Shinsaibashi&destination_place_id=ChIJE0F1JxHnAGARp2gpTuFLvhE&travelmode=walking",
      },
      {
        id: "rden",
        t: "16:25",
        type: "Go",
        name: "Route: Shinsaibashi to Den Den Town",
        what: "Taxi, about 8 min (¥1,000), rather than the 2 km walk.\nOr metro: Shinsaibashi to Namba on the Midosuji Line (1 stop), then Sennichimae Line 1 stop to Nippombashi, about 10 min.",
        dist: "About 2 km · 8 min by taxi",
        hours: "",
        note: "",
        url: "https://www.google.com/maps/dir/?api=1&origin=Asics%20Osaka%20Shinsaibashi&destination=Super%20Potato%20Retro%20Nipponbashi&travelmode=walking",
      },
      {
        id: "den",
        t: "16:30–18:15",
        type: "Shop",
        name: "Den Den Town (Nipponbashi)",
        what: "Osaka's otaku district. Super Potato: retro game shop, floors of old Famicom and Game Boy gear. Suruga-ya: figures, games, cards, manga. Animate Osaka Nipponbashi: new anime goods. Mandarake Grand Chaos: second-hand collectibles",
        dist: "Super Potato to Suruga-ya about 110 m · Animate about 160 m further",
        hours: "Most shops 11:00–20:00 · Suruga-ya 10:00–21:00 · Animate 10:00–20:00 on weekends · Mandarake 12:00–20:00",
        note: "Sunday is busy. Pick two shops. You saw Mandarake in Akihabara and Shibuya already",
        url: "https://www.google.com/maps/dir/?api=1&origin=Super%20Potato%20Retro%20Nipponbashi&destination=Suruga-ya%20Osaka%20Nipponbashi&travelmode=walking",
      },
      {
        id: "chibo",
        t: "18:30",
        type: "Eat",
        name: "CHIBO Dotonbori",
        what: "Okonomiyaki, Osaka's savoury pancake. Known for vegetarian and vegan versions",
        dist: "About 1 km from Super Potato · 12 min",
        hours: "Until 11 pm",
        note: "Ask for no meat, no seafood and no bonito flakes, and ask whether the batter uses fish stock (dashi). Fully vegan alternative: Shojin Sushi Minamo, book ahead",
        url: "https://www.google.com/maps/dir/?api=1&origin=Super%20Potato%20Retro%20Nipponbashi&destination=CHIBO%20Dotonbori&travelmode=walking",
      },
      {
        id: "ebisu",
        t: "19:30",
        type: "See",
        name: "Ebisu Bridge",
        what: "The Glico running man sign and Dotonbori neon",
        dist: "About 300 m from CHIBO · 4 min",
        hours: "",
        note: "",
        url: "https://www.google.com/maps/dir/?api=1&origin=CHIBO+Dotonbori&destination=Ebisu+Bridge&destination_place_id=ChIJdyYZhBPnAGARPF9WeVTYbZM&travelmode=walking",
      },
      {
        id: "tombori",
        t: "19:45",
        type: "See",
        name: "Tombori River Cruise",
        what: "20 min boat ride under the neon",
        dist: "Pier next to Ebisu Bridge",
        hours: "Last boats around 9 pm",
        note: "About ¥2,000; queues grow later",
        url: "https://www.google.com/maps/dir/?api=1&origin=Ebisu+Bridge&origin_place_id=ChIJdyYZhBPnAGARPF9WeVTYbZM&destination=Tombori+River+Cruise&destination_place_id=ChIJ2ySFjBTnAGAR3ngfXW-dwaU&travelmode=walking",
      },
      {
        id: "hozen",
        t: "20:15",
        type: "See",
        name: "Hozenji Yokocho",
        what: "Quiet stone lane with lanterns and a moss-covered shrine",
        dist: "About 100 m from the pier",
        hours: "",
        note: "The goshuin office at Hozenji closes at 18:00, so at 20:15 you can see the lane but not get a stamp",
        url: "https://www.google.com/maps/dir/?api=1&origin=Tombori+River+Cruise&origin_place_id=ChIJ2ySFjBTnAGAR3ngfXW-dwaU&destination=Hozenji+Yokocho&destination_place_id=ChIJY4ZQxRTnAGAR0mjfWQwO7ho&travelmode=walking",
      },
      {
        id: "naruto",
        t: "20:30",
        type: "Eat",
        name: "Naruto Taiyaki Hompo",
        what: "Fish-shaped cake with red bean or custard",
        dist: "About 200 m from Hozenji",
        hours: "Until 5 am",
        note: "Namba Station is about 400 m away",
        url: "https://www.google.com/maps/dir/?api=1&origin=Hozenji+Yokocho&origin_place_id=ChIJY4ZQxRTnAGAR0mjfWQwO7ho&destination=Naruto+Taiyaki+Hompo+Osaka&destination_place_id=ChIJ63rK2mrnAGARmhZZX0xYTw0&travelmode=walking",
      },
      {
        id: "rhome",
        t: "20:50",
        type: "Go",
        name: "Route: Namba to the hotel",
        what: "Namba Station, Midosuji Line (M20) toward Esaka or Senri-Chuo, 2 stops (Shinsaibashi) to Hommachi (M18), about 5 min. Take Exit 4. Exit 5 is closed after 9 pm.",
        dist: "About 15 min door to door",
        hours: "",
        note: "",
        url: "https://www.google.com/maps/dir/?api=1&origin=Namba+Station+Osaka&destination=Osaka+View+Hotel+Honmachi&destination_place_id=ChIJDYCo9OLmAGARHahlNEJ5nhQ&travelmode=transit",
      },
    ],
    tips: [["Package note","Intercity baggage transfer is not included."], ["Not confirmed yet","Whether the Kyoto to Osaka bullet train is in your package, and its time. Trains run about every 10 min, 14 min Kyoto to Shin-Osaka."], ["Shops close at 8 pm","Pokémon Center and Asics close at 8, so the Den Den Town block starts after them on purpose."]],
    sleep: "Osaka View Hotel Honmachi",
  },
  {
    date: "2026-10-26", city: "osaka", title: "Osaka walking tour", short: "Osaka walking tour",
    gist: "Osaka SIC: 1-Day Osaka Walking Tour with Western-style Lunch (round trip from Osaka-Umeda).",
    timeline: [
      ["07:30","Wake up","x"],
      ["08:00","Hotel breakfast","x"],
      ["09:05","Leave the hotel. Midosuji line Hommachi → Umeda (2 stops)","x","respire"],
      ["09:40","Tour starts at Hotel Hankyu Respire Osaka","i"],
      ["","Floating Garden Observatory","i"],
      ["Lunch","Western-style set menu at Hotel Hankyu Respire Osaka","i"],
      ["","Board the Aqua Liner","i"],
      ["","Osaka Castle","i"],
      ["17:45","Tour ends at Higashi-Umeda Station","i"],
      ["18:10","One Piece Mugiwara Store","x","mugi"],
      ["19:00","Dinner: vegan set plate","x","genm"],
      ["19:50","Yodobashi Umeda: toys, Gunpla and cards","x","yodo"],
      ["20:45","Midosuji line Umeda → Hommachi (2 stops)","x","rumeda"],
      ["21:15","Rest, start packing","x"],
      ["22:30","Sleep","x"],
    ],
    places: [
      {
        id: "respire",
        t: "09:05",
        type: "Go",
        name: "Hotel Hankyu Respire Osaka (tour start)",
        what: "Hommachi Exit 4, Midosuji Line (M18) toward Esaka or Senri-Chuo, 2 stops (Yodoyabashi) to Umeda (M16), about 5 min. Then walk to the hotel, about 700 m.",
        dist: "About 25 min door to door",
        hours: "",
        note: "Be there by 9:30",
        url: "https://www.google.com/maps/dir/?api=1&origin=Osaka+View+Hotel+Honmachi&origin_place_id=ChIJDYCo9OLmAGARHahlNEJ5nhQ&destination=Hotel+Hankyu+Respire+Osaka&travelmode=transit",
      },
      {
        id: "ohatsu",
        t: "Also",
        type: "See",
        name: "Tsuyunoten (Ohatsu Tenjin) goshuin",
        what: "Small Umeda shrine. Goshuin ¥500",
        dist: "Near Higashi-Umeda Station, where the tour ends · check the walk in Maps",
        hours: "Office 9:00–18:00",
        note: "The office closes at 18:00, so go straight there if the tour ends on time",
        url: "https://www.google.com/maps/search/?api=1&query=Tsuyunoten%20Shrine%20Ohatsu%20Tenjin%20Osaka",
      },
      {
        id: "mugi",
        t: "18:10",
        type: "Shop",
        name: "One Piece Mugiwara Store Umeda",
        what: "Straw Hat Pirates store with Osaka-only items. It is on 13F of Daimaru Umeda, next to Osaka Station",
        dist: "About 400 m from Higashi-Umeda Station · 5 min. Go to Daimaru 13F",
        hours: "10:00–20:00",
        note: "Nintendo Osaka and Capcom are on the same floor, left out because you did Nintendo in Shibuya",
        url: "https://www.google.com/maps/dir/?api=1&origin=Higashi-Umeda%20Station&destination=Daimaru%20Umeda&travelmode=walking",
      },
      {
        id: "genm",
        t: "19:00",
        type: "Eat",
        name: "Genmian Umeda EST",
        what: "Vegan cafe with a plate of about 15 vegetables, no meat, fish, milk or eggs",
        dist: "About 450 m from Daimaru Umeda · 6 min, in the EST building by HEP FIVE",
        hours: "11:00–22:00 (last order 21:30)",
        note: "2 min walk from Osaka-Umeda Station",
        url: "https://www.google.com/maps/dir/?api=1&origin=Daimaru%20Umeda&destination=Genmian%20Umeda%20EST&travelmode=walking",
      },
      {
        id: "yodo",
        t: "19:50",
        type: "Shop",
        name: "Yodobashi Umeda",
        what: "Giant store with toys, Gunpla, cards and gadgets, next to Osaka Station",
        dist: "A few minutes' walk from Osaka Station (confirm in Maps)",
        hours: "Usually until 22:00, check",
        note: "Closes after the Mugiwara Store, so it fits the evening",
        url: "https://www.google.com/maps/search/?api=1&query=Yodobashi%20Umeda",
      },
      {
        id: "hep",
        t: "Alternative",
        type: "See",
        name: "HEP FIVE Ferris wheel",
        what: "Red 106 m wheel, one 15 min turn over Umeda, lit at night. It's a different view from the Floating Garden you saw in the morning",
        dist: "A few minutes from EST, about 435 m from Daimaru Umeda",
        hours: "11:00–22:45 (last boarding)",
        note: "About ¥1,000 per person. Skip if you're tired. The alternative to Yodobashi if you'd rather ride something",
        url: "https://www.google.com/maps/dir/?api=1&origin=Genmian%20Umeda%20EST&destination=HEP%20FIVE%20Ferris%20Wheel&travelmode=walking",
      },
      {
        id: "rumeda",
        t: "20:45",
        type: "Go",
        name: "Route: Umeda to the hotel",
        what: "Walk 4 min to Umeda Station (M16). Midosuji Line toward Namba, 2 stops (Yodoyabashi) to Hommachi (M18), about 5 min. Take Exit 4. Exit 5 is closed after 9 pm.",
        dist: "About 15 min door to door",
        hours: "",
        note: "",
        url: "https://www.google.com/maps/dir/?api=1&origin=HEP+FIVE+Ferris+Wheel&destination=Osaka+View+Hotel+Honmachi&destination_place_id=ChIJDYCo9OLmAGARHahlNEJ5nhQ&travelmode=transit",
      },
    ],
    tips: [["Package note","Vegetarian meals are available and must be requested at the time of booking."], ["Monday","Daimaru and HEP FIVE are open. Daimaru closes at 20:00."]],
    sleep: "Osaka View Hotel Honmachi",
  },
  {
    date: "2026-10-27", city: "osaka", title: "Universal Studios Japan", short: "Universal Studios Japan",
    gist: "Osaka – Universal Studios (pick and drop transfer, private). Entry ticket only.",
    timeline: [
      ["07:00","Wake up","x"],
      ["07:30","Hotel breakfast","x"],
      ["08:15","Private pickup to Universal Studios (time to confirm)","i"],
      ["09:00","Universal Studios Japan (entry ticket included). Check park hours for the day","i"],
      ["","Super Nintendo World first: Mario Kart, Yoshi, Donkey Kong Country","x","snw"],
      ["","Anime attractions: Jujutsu Kaisen and Chainsaw Man 4-D","x","cool"],
      ["13:00","Lunch inside the park (paid separately)","x"],
      ["16:00","Snack and rest break","x"],
      ["18:00","Halloween Horror Nights starts to take over the park","x","hhn"],
      ["19:30","Dinner at Universal CityWalk, outside the park gates","x","walk"],
      ["21:00","Private drop to the hotel. Ask the agent to move it to about 21:00","i"],
      ["21:30","Back at the hotel. Pack: return flight allows 20 kg check-in and 7 kg cabin each","x"],
      ["22:45","Sleep","x"],
    ],
    places: [
      {
        id: "snw",
        t: "09:00",
        type: "See",
        name: "Super Nintendo World",
        what: "Mario Kart: Koopa's Challenge (AR ride), Yoshi's Adventure, and Donkey Kong Country with its mine-cart ride. Buy a Power-Up Band to collect coins and play interactive blocks. 5th anniversary events run from 10 Sep 2026",
        dist: "Inside the park, a short walk from the entrance",
        hours: "Park listed 8:00–22:00 on Tue 27 Oct",
        note: "Entry to the area is timed. Not confirmed yet whether your ticket includes it. If not, open the USJ app at the gate and take a free Area Timed Entry Ticket. Slots fill fast",
        url: "https://www.google.com/maps/dir/?api=1&origin=Universal%20Studios%20Japan&destination=Super%20Nintendo%20World%20Universal%20Studios%20Japan&travelmode=walking",
      },
      {
        id: "cool",
        t: "Midday",
        type: "See",
        name: "Universal Cool Japan 2026",
        what: "Jujutsu Kaisen: The Real 4-D, a 4-D film with close-range battles. Chainsaw Man: The Chaos 4-D theatre show. Hollywood Dream coaster has a Chainsaw Man overlay with Kenshi Yonezu's IRIS OUT. Detective Conan escape game and Frieren were also announced for 2026",
        dist: "Inside the park",
        hours: "",
        note: "Run dates for each show are not confirmed for 27 Oct. Check the USJ app. The Conan escape game may need a separate timed ticket",
        url: "https://www.google.com/maps/dir/?api=1&origin=Universal%20Studios%20Japan&destination=Jujutsu%20Kaisen%20The%20Real%204-D%20Universal%20Studios%20Japan&travelmode=walking",
      },
      {
        id: "hhn",
        t: "18:00",
        type: "See",
        name: "Halloween Horror Nights",
        what: "Runs 11 Sep–8 Nov 2026. After 18:00 the park fills with zombies and scare actors. Your ride home is at 19:00 so you see the first hour",
        dist: "Across the park",
        hours: "After 18:00",
        note: "Some scare zones are loud and crowded. Decide on the day",
        url: "https://www.google.com/maps/dir/?api=1&origin=Universal%20Studios%20Japan&destination=Universal%20Studios%20Japan&travelmode=walking",
      },
      {
        id: "walk",
        t: "19:30",
        type: "Eat",
        name: "Universal CityWalk Osaka",
        what: "Restaurants and shops outside the park gates, so dinner needs no taxi",
        dist: "Right outside the gate of Universal Studios Japan",
        hours: "Roughly 10:00–22:00, check",
        note: "Vegetarian options not checked yet, so look at the menus first. Fallback: Pivot BASE in Dotonbori, open to midnight",
        url: "https://www.google.com/maps/search/?api=1&query=Universal%20CityWalk%20Osaka",
      },
      {
        id: "pivot",
        t: "Fallback",
        type: "Eat",
        name: "Pivot BASE Cafe and Bar",
        what: "Fully vegan: takoyaki, yakisoba, ramen, fried skewers. Osaka street food without fish or meat",
        dist: "Midosuji Line Hommachi → Namba, 2 stops (M20), then about 600 m walk, 8 min",
        hours: "11:30–midnight per listings",
        note: "English menu. Hours not confirmed, check on Google Maps. Home: Namba to Hommachi, 2 stops, Exit 4",
        url: "https://www.google.com/maps/dir/?api=1&origin=Osaka+View+Hotel+Honmachi&origin_place_id=ChIJDYCo9OLmAGARHahlNEJ5nhQ&destination=Pivot%20BASE%20Cafe%20Dotonbori&travelmode=transit",
      },
    ],
    tips: [["Ask the agent","Pickup and drop times for the Universal Studios transfer, whether the drop can move to about 21:00, and whether the ticket includes Super Nintendo World timed entry."], ["Tuesday","Park hours are listed as 8:00 to 22:00. Your itinerary says 9:00, so ask whether the transfer arrives earlier."]],
    sleep: "Osaka View Hotel Honmachi",
  },
  {
    date: "2026-10-28", city: "travel", title: "Fly home (Dad to China)", short: "Fly home (Dad to China)",
    gist: "Airport transfer, one way (private). Thai Vietjet, 1 stop in Bangkok. Dhairya and Sweta fly home. Dad flies on to China separately.",
    timeline: [
      ["06:45","Wake up","x"],
      ["07:15","Hotel breakfast","x"],
      ["08:00","Check out","x"],
      ["08:15","Private transfer to the airport (time to confirm)","i"],
      ["~09:15","Reach Kansai (KIX), check in. 20 kg check-in, 7 kg cabin","x"],
      ["12:00","VZ 567 departs Kansai (KIX)","i"],
      ["18:10","Lands Bangkok (BKK), 4h 20m layover, change planes","i"],
      ["22:30","VZ 770 departs Bangkok","i"],
      ["23:50","Lands Kolkata (CCU)","i"],
    ],
    places: [
    ],
    tips: [["Itinerary error","The itinerary says transfer from Narita. Your flight leaves from Kansai (KIX)."], ["Baggage","Cabin 7 kg and check-in 20 kg per adult."]],
    sleep: "Home",
  },
];

export const FLIGHTS = [
  {
    route: "Kolkata → Delhi → Tokyo",
    when: "Mon 19 Oct · 12:55 → Tue 20 Oct 05:55",
    lines: [
      "AI 1874 Kolkata → Delhi, then AI 358 → Haneda T3",
      "13h 30m, 1 stop in Delhi",
      "Meals complimentary",
    ],
    who: "Dhairya, Dilip and Sweta Khetan",
  },
  {
    route: "Osaka → Bangkok → Kolkata",
    when: "Wed 28 Oct · 12:00 → 23:50 same night",
    lines: [
      "Thai Vietjet VZ 567 from Kansai (KIX), 4h 20m stop in Bangkok, then VZ 770",
      "20 kg check-in + 7 kg cabin each",
    ],
    who: "Dhairya and Sweta Khetan. Dad flies on to China separately.",
  },
];

export const HOTELS: { nights: string; name: string; room: string; city: City; address: string; checkIn: string; checkOut: string; note: string }[] = [
  {
    nights: "20, 21, 22 Oct", name: "Citadines Shinjuku Tokyo", room: "Studio double, breakfast included", city: "tokyo",
    address: "1-28-13 Shinjuku, Shinjuku-ku, Tokyo", checkIn: "15:00", checkOut: "11:00",
    note: "Three adults share a studio double, so the hotel may charge for the extra person at check-in. Bring photo ID, a deposit may be asked. Late check-out costs extra.",
  },
  {
    nights: "23, 24 Oct", name: "Miyako Hotel Kyoto Hachijo", room: "South Wing twin, non-smoking, breakfast included", city: "kyoto",
    address: "17 Nishi Kujoin-machi, Minami-ku, Kyoto 601-8412", checkIn: "14:00", checkOut: "11:00",
    note: "2 minutes' walk from the Hachijo (south) exit of Kyoto Station. The hotel may charge for the third guest at check-in.",
  },
  {
    nights: "25, 26, 27 Oct", name: "Osaka View Hotel Honmachi", room: "Standard triple, non-smoking, breakfast included", city: "osaka",
    address: "4-5-2 Honmachi, Chuo-ku, Osaka 541-0053", checkIn: "15:00", checkOut: "11:00",
    note: "Check-in is open until midnight. City tax is ¥0, paid at the hotel.",
  },
];

export const TODO = [
  "Pickup point for the Tokyo half-day tour (20 Oct).",
  "Starting point for the Mt. Fuji tour (21 Oct).",
  "Pickup and return times for Disney (22 Oct) and Universal Studios (27 Oct), and whether the 27 Oct drop can move to about 21:00.",
  "Tour end time on 24 Oct, and which Nara sights the bus visits.",
];

/** Every temple and shrine near the route that gives a goshuin. `status` says how it fits. */
export type SpotStatus = "plan" | "tour" | "fit" | "detour";
export type Spot = {
  area: string; city: City; kind: string; status: SpotStatus; name: string;
  when: string; price: string; hours: string; where: string; note: string; url: string;
};

export const SPOTS: Spot[] = [
  {
    area: "Tokyo", city: "tokyo", kind: "Temple", status: "plan", name: "Senso-ji",
    when: "20 Oct, on the tour",
    price: "¥300 a stamp, two designs. Goshuincho ¥1,500–5,000",
    hours: "Counter 8:00–16:30",
    where: "Yogodo Hall, west of the main hall, about 600 m in from Kaminarimon",
    note: "Buy your goshuincho here, and get the stamp before the shopping. Weekday queue can be 10–30 min. Bring coins.",
    url: "https://www.google.com/maps/dir/?api=1&origin=Kaminarimon%20Asakusa&destination=Senso-ji%20Temple%20Asakusa&travelmode=walking",
  },
  {
    area: "Tokyo", city: "tokyo", kind: "Shrine", status: "tour", name: "Asakusa Shrine",
    when: "20 Oct, next to Senso-ji",
    price: "¥500",
    hours: "Weekdays 9:00–16:00",
    where: "Beside the Senso-ji main hall",
    note: "A second stamp from the same visit. Do it before 16:00.",
    url: "https://www.google.com/maps/search/?api=1&query=Asakusa%20Shrine%20Tokyo",
  },
  {
    area: "Tokyo", city: "tokyo", kind: "Shrine", status: "fit", name: "Meiji Jingu",
    when: "23 Oct, Harajuku, if you are ahead of time",
    price: "¥500. Goshuincho ¥1,500–2,000",
    hours: "Office roughly 8:00–16:30. The shrine follows sunrise and sunset",
    where: "1 min from Harajuku Station to the gate. The office is at Nagado Hall, a longer walk into the grounds",
    note: "Needs about 40 minutes with the walk in. Skip it if lunch is already late.",
    url: "https://www.google.com/maps/search/?api=1&query=Meiji%20Jingu",
  },
  {
    area: "Tokyo", city: "tokyo", kind: "Shrine", status: "fit", name: "Hanazono Shrine",
    when: "20 Oct morning, or any morning in Shinjuku",
    price: "¥500–1,000, sources differ",
    hours: "Office from about 9:00. Closing time is not reliable, so go in the morning",
    where: "In Shinjuku, a short taxi from the hotel (check in Maps)",
    note: "Small and quick. It also has a paper-cut (kirie) design for about ¥1,000.",
    url: "https://www.google.com/maps/search/?api=1&query=Hanazono%20Shrine%20Shinjuku",
  },
  {
    area: "Tokyo", city: "tokyo", kind: "Shrine", status: "detour", name: "Kanda Myojin",
    when: "Akihabara, only in the daytime",
    price: "¥500",
    hours: "Goshuin until 17:00",
    where: "Near Akihabara and Ochanomizu",
    note: "The anime-collab shrine (Love Live and others). The office is shut by the time you reach Akihabara at 18:00 on 20 Oct, so only a jet-lag morning would work.",
    url: "https://www.google.com/maps/search/?api=1&query=Kanda%20Myojin%20Shrine",
  },
  {
    area: "Mt. Fuji", city: "tokyo", kind: "Shrine", status: "plan", name: "Fujisan Komitake Shrine",
    when: "21 Oct, at the 5th Station",
    price: "Price not confirmed",
    hours: "Office 8:30–16:30",
    where: "Behind the shops at the Fuji Subaru Line 5th Station",
    note: "The stamp shows Mt. Fuji and cherry blossom. Bring the goshuincho from Senso-ji.",
    url: "https://www.google.com/maps/dir/?api=1&origin=Fuji%20Subaru%20Line%205th%20Station&destination=Fujisan%20Komitake%20Shrine&travelmode=walking",
  },
  {
    area: "Kyoto", city: "kyoto", kind: "Shrine", status: "fit", name: "Nishiki Tenmangu",
    when: "25 Oct morning, at the end of Nishiki Market",
    price: "Price not confirmed",
    hours: "Shrine 8:00–20:00. Stamp hours not confirmed",
    where: "East end of Nishiki Market, at Teramachi. Taxi to the west end and walk east, about 400 m",
    note: "A small shrine squeezed between shops. Costs no extra travel.",
    url: "https://www.google.com/maps/search/?api=1&query=Nishiki%20Tenmangu%20Kyoto",
  },
  {
    area: "Kyoto", city: "kyoto", kind: "Temple", status: "fit", name: "Toji",
    when: "25 Oct early, before check-out",
    price: "Varies by design. One source lists ¥2,000 for a special one, so check the board",
    hours: "Temple 8:00–17:00. The halls cost ¥800",
    where: "Near the Kyoto hotel in Minami-ku, a short taxi (check in Maps)",
    note: "Japan's tallest wooden pagoda. Needs breakfast by 07:30 and a 08:15 start.",
    url: "https://www.google.com/maps/search/?api=1&query=Toji%20Temple%20Kyoto",
  },
  {
    area: "Kyoto", city: "kyoto", kind: "Shrine", status: "plan", name: "Fushimi Inari Taisha",
    when: "24 Oct, on the tour",
    price: "¥500",
    hours: "Office 8:30–16:30",
    where: "On the tour route, at the base of the mountain",
    note: "If the tour reaches Fushimi Inari after 16:30, the office is closed. Ask your guide when you'll be there.",
    url: "https://www.google.com/maps/dir/?api=1&origin=Fushimi%20Inari%20Taisha&destination=Fushimi%20Inari%20Taisha%20Shamusho&travelmode=walking",
  },
  {
    area: "Kyoto", city: "kyoto", kind: "Temple", status: "tour", name: "Tenryu-ji, Arashiyama",
    when: "24 Oct, if the Arashiyama stop includes it",
    price: "Price not confirmed",
    hours: "Stamps 9:00–16:30. Garden 8:30–17:00",
    where: "Arashiyama, near the bamboo grove",
    note: "Entry ¥500, and ¥300 more for the buildings.",
    url: "https://www.google.com/maps/search/?api=1&query=Tenryu-ji%20Arashiyama",
  },
  {
    area: "Kyoto", city: "kyoto", kind: "Temple", status: "detour", name: "Kiyomizu-dera",
    when: "Not on your plan",
    price: "¥300",
    hours: "6:00–18:00. Entry ¥500",
    where: "Higashiyama, a long uphill walk from the nearest road",
    note: "Worth it for the view, but the slope is much longer than 600 m. Hard for your parents.",
    url: "https://www.google.com/maps/search/?api=1&query=Kiyomizu-dera%20Kyoto",
  },
  {
    area: "Kyoto", city: "kyoto", kind: "Shrine", status: "detour", name: "Yasaka Shrine, Gion",
    when: "Daytime only",
    price: "¥500",
    hours: "Office 9:00–16:00. Grounds open 24 hours",
    where: "Gion, taxi from the hotel",
    note: "You could pass it on an evening walk, but the office would be closed.",
    url: "https://www.google.com/maps/search/?api=1&query=Yasaka%20Shrine%20Kyoto",
  },
  {
    area: "Nara", city: "kyoto", kind: "Temple", status: "plan", name: "Todai-ji",
    when: "24 Oct, if the tour stops there",
    price: "¥300 a stamp, several designs. Notebooks ¥900–2,000",
    hours: "Great Buddha Hall 7:30–17:30 (Apr–Oct). Other halls 8:30–16:00",
    where: "Nara Park",
    note: "Great Buddha Hall entry ¥800.",
    url: "https://www.google.com/maps/search/?api=1&query=Todai-ji%20Nara",
  },
  {
    area: "Nara", city: "kyoto", kind: "Shrine", status: "tour", name: "Kasuga Taisha",
    when: "24 Oct, only if the bus goes there",
    price: "¥500",
    hours: "6:30–17:30 (Mar–Oct)",
    where: "Nara Park, further than 600 m from Todai-ji",
    note: "The stone-lantern shrine. Ask the guide whether the stop is long enough.",
    url: "https://www.google.com/maps/search/?api=1&query=Kasuga%20Taisha%20Nara",
  },
  {
    area: "Osaka", city: "osaka", kind: "Temple", status: "fit", name: "Hozenji",
    when: "25 Oct, before 18:00",
    price: "¥500, four designs",
    hours: "Office 10:00–18:00",
    where: "Hozenji lane, between Namba and Dotonbori",
    note: "The plan reaches the lantern lane at 20:15, after the office shuts. Visit before dinner, or see the lane at night and skip the stamp.",
    url: "https://www.google.com/maps/search/?api=1&query=Hozenji%20Temple%20Osaka",
  },
  {
    area: "Osaka", city: "osaka", kind: "Shrine", status: "fit", name: "Namba Yasaka Shrine",
    when: "25 Oct afternoon",
    price: "¥300–500, sources differ",
    hours: "Shop 9:00–16:30. Grounds open 24 hours",
    where: "Namba area, short taxi",
    note: "The lion-head stage is a five-minute photo. Daytime only.",
    url: "https://www.google.com/maps/search/?api=1&query=Namba%20Yasaka%20Shrine",
  },
  {
    area: "Osaka", city: "osaka", kind: "Shrine", status: "tour", name: "Hokoku Shrine, Osaka Castle",
    when: "26 Oct, if the tour gives free time at the castle",
    price: "¥300",
    hours: "9:00–16:50",
    where: "In Osaka Castle Park",
    note: "Dedicated to Toyotomi Hideyoshi, who built the castle. Free entry.",
    url: "https://www.google.com/maps/search/?api=1&query=Hokoku%20Shrine%20Osaka",
  },
  {
    area: "Osaka", city: "osaka", kind: "Shrine", status: "fit", name: "Tsuyunoten (Ohatsu Tenjin), Umeda",
    when: "26 Oct, right after the tour ends",
    price: "¥500",
    hours: "Office 9:00–18:00. The shrine is open 6:00–24:00",
    where: "Near Higashi-Umeda Station, where the tour ends at 17:45 (check the walk in Maps)",
    note: "The office closes at 18:00, so go straight there.",
    url: "https://www.google.com/maps/search/?api=1&query=Tsuyunoten%20Shrine%20Ohatsu%20Tenjin%20Osaka",
  },
  {
    area: "Osaka", city: "osaka", kind: "Temple and shrine", status: "detour", name: "Shitennoji and Sumiyoshi Taisha",
    when: "Not on your plan",
    price: "Price and hours not checked",
    hours: "Not checked",
    where: "South Osaka, 20 minutes or more by taxi each way",
    note: "Osaka's oldest temple and the sea-god shrine. Only if you give up a block of the day.",
    url: "https://www.google.com/maps/search/?api=1&query=Shitennoji%20Osaka",
  },
];

/** Short reference lists under the planner: [bold lead, rest]. */
export const GOSHUIN: Row[] = [
  ["Goshuincho (stamp book)", "buy one at Senso-ji on 20 Oct, about ¥1,500 for a plain book and ¥3,000 to ¥5,000 for fancier covers."],
  ["Fuji and Hakone", "Fuji-shaped omamori and wooden charms at the 5th Station, black eggs (kuro-tamago) at Owakudani. Hakone is the model for Evangelion's Tokyo-3, so look for Eva goods at the ropeway shops (not confirmed for October)."],
  ["Anime and games", "Akihabara (20 Oct), Tokyo Station Character Street (21 Oct), Uniqlo UT and Graniph in Harajuku (23 Oct), Kyoto Manga Museum shop (25 Oct), Pokémon Center Osaka DX, Shinsaibashi PARCO and Den Den Town (25 Oct), One Piece Mugiwara Store (26 Oct)."],
  ["Weight", "20 kg check-in and 7 kg cabin each on the flight home. Buy figures last and keep the boxes small."],
];

export const METRO: Row[] = [
  ["Card", "a Suica, PASMO or ICOCA works on every metro and JR line in all three cities. Tap on the gate going in and going out."],
  ["Station codes", "each stop has a line letter and number, for example Marunouchi M10 Shinjuku-gyoemmae, Fukutoshin F13 Shinjuku-sanchome, Midosuji M18 Hommachi. Count stops with these."],
  ["Exits", "big stations have dozens. The route cards give the exit number, follow the yellow exit signs."],
  ["Hotels", "Tokyo, Shinjuku-gyoemmae Exit 2 (5 min walk) or Shinjuku-sanchome Exit C7 (7 min). Kyoto, 2 min from the Hachijo (south) exit of Kyoto Station. Osaka, Hommachi Exit 4 (2 min); Exit 5 closes after 9 pm and on weekends."],
  ["Late trains", "most lines stop around midnight. Check the last train in Google Maps before you leave after 10 pm."],
  ["JR local vs rapid", "for Akihabara take the yellow Chuo-Sobu local. The orange Chuo Rapid does not stop there."],
];
